#DP-50: Improve readme file
atlp-rwanda/atlp-pulse-fn pull request #13
Opened 2022-07-07 23:26 UTC by feyton

### What the PR does:
The PR add information about the project to our base README file to give people an overview

### Description of tasks to be completed:
- [ ] Running instructions are added
- [ ] Important links (Figma) are added

### How can this be manually tested
Check out this branch and navigate to the README file

2022-07-11 16:49 UTC, samyshyaka requested changes
Good job @feyton, attend to the feedback below.

2022-07-11 16:49 UTC, samyshyaka commented on README.md
> +Pulse is a platform designed to handle ratings for the companies in the **Edu-tech** industries with the its first paying customer being **Andela**. It is currently under development using modern web
It is Ed-tech, not Edu-tech

2022-07-11 16:49 UTC, samyshyaka commented on README.md
> +#### atlp-pulse-fn
Here, you can use the name of the product as the title

2022-07-11 17:09 UTC, samyshyaka approved these changes

2022-07-11 17:24 UTC, Julesbi approved these changes

2022-07-12 07:38 UTC, ceelogre approved these changes

2022-07-12 07:58 UTC, Julesbi commented
Resolve conflicts and get merged

2022-07-12 09:11 UTC, merged