Bug(DP-108):Fix URI naming
atlp-rwanda/atlp-pulse-fn pull request #130
Opened 2022-10-05 18:54 UTC by Procech20

### PR description 
_Fixing URI naming_
### What this PR does
- Fix login URI name
- Fix organization login URI names
- Remove URIs that are no longer in use
### How can it be tested
Go to the app, and navigate to sognin, the organization login should now be `/organization-login`, and the the login uri should now be `/login`.
### Background context
Successfully merging this PR will introduce new names in the links that are more realistic and easier to understand by any user
### Relevant trello ID
[#DP-108](https://trello.com/c/EQl3uwYN/108-fix-login-uri)
### Screenshot
_N/A_
### Checks completed
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My test coverage meet the set test coverage threshold
- [x] There are no conflicts with the base branch

2022-10-05 18:56 UTC, Procech20 commented
I deployed a review app for you to try out this pull request 👇🏽

Heroku App: https://devpulse-review-app-130.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

2022-10-06 09:31 UTC, ceelogre requested changes
Change `organization-login` to `login/org`

2022-10-06 15:31 UTC, ceelogre commented
It seems you forgot to prefix it with the app's uri
<img width="952" alt="image" src="https://user-images.githubusercontent.com/5022823/194355300-116ea60b-3b88-40cd-a38b-872bc309f1d6.png">

Also while you're here, can you also change the `/register-org` to `signup/org`

2022-10-06 20:59 UTC, Procech20 commented
@alaintresor the 404 page is nowhere to be found.

![404_page.png](https://user-images.githubusercontent.com/75941936/194417334-74185acf-44e2-4431-9e41-d1a9ec7653f6.png)

2022-10-07 05:58 UTC, alaintresor commented
> @alaintresor the 404 page is nowhere to be found.
> 
> ![404_page.png](https://user-images.githubusercontent.com/75941936/194417334-74185acf-44e2-4431-9e41-d1a9ec7653f6.png)

It is now fixed

2022-10-07 07:59 UTC, ceelogre commented
This should be the correct 404.
![image](https://user-images.githubusercontent.com/5022823/194503154-c26de2b7-66d9-4428-9c8a-0b569e9ea7ea.png)

2022-10-07 08:47 UTC, Placide123 reviewed
seems likes there other routes that are not working 
https://user-images.githubusercontent.com/86245638/194510995-ac8f1c91-8350-48f2-9662-cfc9b0640f4e.mov

2022-10-07 13:09 UTC, ceelogre approved these changes

2022-10-07 13:09 UTC, merged