Fix Coverage
atlp-rwanda/atlp-pulse-fn pull request #136
Opened 2022-10-13 09:39 UTC by ElissaDesign

# PR Description
This PR fixes the coverage by increasing it above 80% 

# Description of tasks that were expected to be completed

1. Checking if there are the task which needs to be tested and write the tests
2. Checking open branches if they meet with the coverage needed(no reduction of coverage) if so , write test to increase the coverage

# How has this been tested?

1. Clone this RP
2. Install needed Depencencies by runing `npm install`
3. Add environment variables check `.env.example`
4. After run `npm run coverage` 

# Number of Commits
1
# Screenshots (If appropriate)
N/A

# Please check this Checklist before you submit your PR:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

2022-10-20 08:03 UTC, Procech20 commented
I deployed a review app for you to try out this pull request 👇🏽
Heroku App: https://devpulse-review-app-136.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

2022-10-21 12:29 UTC, alicepretty approved these changes

2022-10-21 12:55 UTC, alaintresor approved these changes

2022-10-24 06:20 UTC, Julienish14 approved these changes

2022-10-24 11:31 UTC, Francoise02 approved these changes

2022-10-24 11:34 UTC, Placide123 approved these changes

2022-10-25 10:26 UTC, ceelogre requested changes
There was an overuse of the `ignore` rule. Go through the files again and add more tests.

2022-10-25 10:26 UTC, ceelogre commented on src/hook/useAuth.tsx
>    };
Should not be ignored.

2022-10-25 10:26 UTC, ceelogre commented on src/pages/AdminTraineeDashboard.tsx
>      setRemoveTraineeModel(newState);
A lot of lines in the file can be tested.

2022-10-27 20:17 UTC, ceelogre approved these changes

2022-10-27 20:19 UTC, merged