Feature: Display trainees in cohort
atlp-rwanda/atlp-pulse-fn pull request #143
Opened 2022-10-20 13:46 UTC by alaintresor

# PR Description

It displays every trainee include in a cohort

# Description of tasks that were expected to be completed

- Create a new trainee modal that displays all trainees in a cohort 

# How has this been tested?

- Login as admin
- Go to the Cohort menu
- Click on the people icon to get all trainees that include in that cohort

# Number of Commits

1 commit

# Screenshots (If appropriate)
![Screenshot (3)](https://user-images.githubusercontent.com/55650162/196964903-91c819bb-3f86-460e-a74a-a8d5fa20b439.png)
![Screenshot (2)](https://user-images.githubusercontent.com/55650162/196965451-4bc485e1-9abe-4cc1-8e9f-f01afbe98ad7.png)

# Please check this Checklist before you submit your PR:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

2022-10-20 20:22 UTC, Procech20 commented
I deployed a review app for you to try out this pull request 👇🏽
Heroku App: https://devpulse-review-app-143.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

2022-10-21 13:13 UTC, Placide123 approved these changes

2022-10-21 13:21 UTC, alicepretty approved these changes

2022-10-21 13:31 UTC, Dev-nkundineza approved these changes

2022-10-21 13:47 UTC, Procech20 approved these changes

2022-10-21 16:38 UTC, Procech20 requested changes, later dismissed
Am getting an error that says "Not logged in an organization yet I did"!

2022-10-21 18:55 UTC, alaintresor commented
>



> Am getting an error that says "Not logged in an organization yet I did"!

It's now fixed, please try it again

2022-10-24 18:55 UTC, ceelogre reviewed
You can respond to my comment then we proceed with merging.

2022-10-24 18:55 UTC, ceelogre commented on src/containers/admin-dashBoard/CohortTraineeModal.tsx
> +      datum[index].name = data.profile ? data.profile.name : 'undefined';
Why did we re-introduce `undefined` for profile names?

2022-10-26 11:46 UTC, closed without merging