Fix: Landing pages
atlp-rwanda/atlp-pulse-fn pull request #15
Opened 2022-07-10 22:20 UTC by jeandamascyifuzo

- Fix the dark theme preferences
- Fix the arrangement of items

<img width="1439" alt="Screen Shot 2022-07-11 at 00 16 44" src="https://user-images.githubusercontent.com/87600918/178164055-8cba40db-f67a-4105-a9f8-950f142b62eb.png">

2022-07-11 06:16 UTC, IIshimwe commented
Improve on toggle of light mode and dark mode when hovered over it to show that it is clickable by changing the mouse to cursor.

2022-07-11 06:48 UTC, feyton approved these changes
### Approval

These changes are well implemented @jeandamascyifuzo

2022-07-11 10:30 UTC, feyton approved these changes

2022-07-11 11:01 UTC, samyshyaka requested changes
Good Job @jeandamascyifuzo & @feyton. Attend to the feedback below 
- The margin on the right of the svg should be equal to the margin on the left of the 'Welcome to DevPulse' text. 
- Also, add some margin at the top of the svg

2022-07-11 16:35 UTC, samyshyaka approved these changes

2022-07-12 07:34 UTC, ceelogre approved these changes

2022-07-12 07:34 UTC, merged