404 login redirect
atlp-rwanda/atlp-pulse-fn pull request #168
Opened 2022-11-10 08:45 UTC by elissaihimbazwe

# PR Description
This PR checks if the token in local storage is expired if true you will be redirected to the 404 page 

# Description of tasks that were expected to be completed

1. validation of token in local storage
2. page redirect
3. Test writing if needed

# How has this been tested?

Login with valid credentials, you will be given a token which will last for 1 minute
 after the expiration you will be redirected to login page

# Number of Commits
1 commit

# Screenshots (If appropriate)
N/A

# Please check this Checklist before you submit your PR:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My code generate no warnings
- [x] My test coverage meet the set test coverage threshold
- [x] There are no vulnerabilities
- [x] There are no conflicts with the base branch

2022-11-10 12:41 UTC, ElissaDesign commented
I deployed a review app for you to try out this pull request 👇🏽
Heroku App: https://devpulse-review-app-168.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

2022-11-10 18:09 UTC, Placide123 approved these changes

2022-11-10 19:18 UTC, alaintresor approved these changes

2022-11-10 19:28 UTC, Placide123 approved these changes

2022-11-10 19:55 UTC, Francoise02 approved these changes

2022-11-10 19:56 UTC, Julienish14 approved these changes

2022-11-11 09:22 UTC, ishimweeli approved these changes

2022-11-11 10:11 UTC, ceelogre requested changes

2022-11-11 10:11 UTC, ceelogre commented on src/utils/PrivateRoute.tsx
> +
This is not the best way to implement this feature. You do not need to keep checking if the token has expired so you can logout a user, instead, you wanna wait for them to perform a certain action then when they send a request along its token, check if it has expired and re-route them to login page *with a message that they got logged out due to inactivity*

2022-11-14 18:55 UTC, closed without merging