fix app translations
atlp-rwanda/atlp-pulse-fn pull request #169
Opened 2022-11-10 14:48 UTC by alaintresor

# PR Description

Fix #167 issue

# Description of tasks that were expected to be completed

List all the tasks and sub-tasks that were assigned to you or that you assigned yourself. Make sure you check evey completed task.

# How has this been tested?

Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

# Number of Commits

The number of commits should not exceed **2 commits**. In case they are more than that, please take your time and squash them.

# Screenshots (If appropriate)

# Please check this Checklist before you submit your PR:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

2022-11-10 14:51 UTC, ElissaDesign commented
I deployed a review app for you to try out this pull request 👇🏽
Heroku App: https://devpulse-review-app-169.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

2022-11-10 16:29 UTC, Julienish14 approved these changes

2022-11-10 16:51 UTC, Placide123 approved these changes

2022-11-10 16:52 UTC, alicepretty approved these changes

2022-11-10 19:27 UTC, ElissaDesign approved these changes

2022-11-11 08:29 UTC, ishimweeli approved these changes

2022-11-11 09:20 UTC, ceelogre requested changes

2022-11-11 09:20 UTC, ceelogre commented on src/components/ButtonLoading.tsx
> +        {t('Processing...')}
Processing word does not make sense here. Something like `signing you in` is more relatable.

2022-11-11 09:52 UTC, ceelogre approved these changes

2022-11-11 09:52 UTC, merged