fix expired org token
atlp-rwanda/atlp-pulse-fn pull request #178
Opened 2022-11-16 13:54 UTC by alaintresor

# PR Description

fix #174 issue

# Description of tasks that were expected to be completed

List all the tasks and sub-tasks that were assigned to you or that you assigned yourself. Make sure you check evey completed task.

# How has this been tested?

Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

# Number of Commits

The number of commits should not exceed **2 commits**. In case they are more than that, please take your time and squash them.

# Screenshots (If appropriate)

# Please check this Checklist before you submit your PR:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

2022-11-16 13:57 UTC, ElissaDesign commented
I deployed a review app for you to try out this pull request 👇🏽
Heroku App: https://devpulse-review-app-178.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

2022-11-22 06:52 UTC, Placide123 approved these changes

2022-11-22 14:50 UTC, ceelogre requested changes
Org token expired after about two hours.
![image](https://user-images.githubusercontent.com/5022823/203344708-458b0025-0fa1-4dc6-a91f-b2ac4de7a6f9.png)

2022-11-23 18:20 UTC, alicepretty approved these changes

2022-11-25 09:22 UTC, Julienish14 approved these changes

2022-11-25 15:36 UTC, ceelogre approved these changes

2022-11-25 15:37 UTC, merged