Fix ratings issues
atlp-rwanda/atlp-pulse-fn pull request #187
Opened 2022-11-27 13:52 UTC by Himbaza123h

# PR Description

1. Fixing rating issues

# Description of tasks that were expected to be completed

1. Rating a trainee according to his/ her performance

# How has this been tested?
1. Open the review app link.
2. Login in as coordinator, add a trainee to a cohort
3. Go to rating and rate a trainee according to his/her performance 

Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

# Number of Commits

The number of commits should not exceed **2 commits**. In case they are more than that, please take your time and squash them.

# Screenshots (If appropriate)

<img width="1439" alt="Screen Shot 2022-11-27 at 15 41 42" src="https://user-images.githubusercontent.com/100874204/204138464-4e925248-8e23-4b5c-b025-284f9cc5e9f4.png">

# Please check this Checklist before you submit your PR:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

2022-11-27 13:58 UTC, ElissaDesign commented
I deployed a review app for you to try out this pull request 👇🏽
Heroku App: https://devpulse-review-app-187.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

2022-12-09 09:11 UTC, Placide123 requested changes, later dismissed
the translation is not working

2022-12-13 11:26 UTC, alicepretty approved these changes

2022-12-14 14:56 UTC, Julienish14 approved these changes

2022-12-14 15:14 UTC, ceelogre commented
This is the list of trainees for cohort 1
![image](https://user-images.githubusercontent.com/5022823/207633301-369d56f6-4831-453b-b510-f3fb04aa9ba1.png)

![image](https://user-images.githubusercontent.com/5022823/207633551-4ef1669e-24f4-4d47-9e63-683f72220b5c.png)

Trainees are unable to view their performance after login.
![image](https://user-images.githubusercontent.com/5022823/207632865-8b3f5357-f9ea-49d9-aa8d-1a94e31acaeb.png)

2022-12-15 08:26 UTC, ishimweeli approved these changes

2022-12-15 12:06 UTC, ceelogre approved these changes

2022-12-15 12:06 UTC, merged