#DP-56 fix: Register Organisation page fixes
atlp-rwanda/atlp-pulse-fn pull request #19
Opened 2022-07-12 07:27 UTC by jeandamascyifuzo

### What the PR does:
Fix the arrangement of items
Fix the design of the register form

### How should this be manually tested:

git clone <project>
git checkout **ft-OrgRegister-fixes**
npm install
npm run dev
open http://localhost:3000

### Screenshot 
<img width="1440" alt="Screen Shot 2022-07-12 at 09 20 24" src="https://user-images.githubusercontent.com/87600918/178432800-fc51926c-ce0a-467d-a83b-4e0612a09bd0.png">
<img width="220" alt="Screen Shot 2022-07-12 at 09 22 12" src="https://user-images.githubusercontent.com/87600918/178433084-8cc29fa1-a671-4f41-bdb9-6660641be00e.png">

2022-07-12 08:31 UTC, chanceDira requested changes
Good job, 
I just left some reviews for you.

2022-07-12 08:31 UTC, chanceDira commented on src/pages/OrgRegister.tsx
> +              src={Logo}
I think as we have a logo on the header, It will be better if we remove this logo.

2022-07-12 08:31 UTC, chanceDira commented on src/pages/OrgRegister.tsx
> +        <div className='hidden bg-[#1F2A37] dark:bg-[#262E3D] px-8 py-4 h-screen lg:w-[45%] lg:flex lg:flex-col grow pt-24'>
If possible we can have gray bg on the light theme.

2022-07-12 09:47 UTC, Julesbi approved these changes

2022-07-12 10:01 UTC, chanceDira approved these changes

2022-07-12 10:42 UTC, feyton approved these changes
### Approval

Hello @jeandamascyifuzo , this is well implemented. Despite the approval I left some comment that work noting down and leave your view on them

2022-07-12 10:42 UTC, feyton commented on src/pages/OrgRegister.tsx
> +              PULSE
Can we change the word from **Pulse** to **Getting started** as title. We already have the app name in many places.

Leave your opinion based on this screenshot

![image](https://user-images.githubusercontent.com/28519395/178472233-3286927b-f090-4702-a404-d75b27c8ccc2.png)

2022-07-12 15:29 UTC, ceelogre requested changes
A small change in dimensions renders the page unresponsive.  Take a look at the screenshot below. Words in the right section have spelling errors and uneven spacing.

<img width="1256" alt="image" src="https://user-images.githubusercontent.com/5022823/178527199-981e843f-b411-4b52-ace4-8f154e4c9291.png">

2022-07-13 11:30 UTC, ceelogre reviewed
Resolve conflicts and add a review app.

2022-07-13 11:47 UTC, feyton commented
I deployed a review app for you to try out this pull request 👇🏽

Heroku App: https://devpulse-review-app-19.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

2022-07-13 11:48 UTC, jeandamascyifuzo commented
> 

good

2022-07-13 12:47 UTC, ceelogre commented
Good job with the responsiveness however, the text on the left still have spelling errors.

2022-07-14 08:27 UTC, ceelogre requested changes
Change the text to: 

> With your own organization, you get a custom domain where you can manage your trainees/students and you can handle all process related to your program.

2022-07-14 09:08 UTC, ceelogre approved these changes

2022-07-14 09:09 UTC, merged