Feature: Create team into cohort
atlp-rwanda/atlp-pulse-fn pull request #192
Opened 2022-12-08 19:14 UTC by Placide123

# PR Description

Please include a brief description of the pull request you want to raise.

# Description of tasks that were expected to be completed

List all the tasks and sub-tasks that were assigned to you or that you assigned yourself. Make sure you check evey completed task.

# How has this been tested?

Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

# Number of Commits

The number of commits should not exceed **2 commits**. In case they are more than that, please take your time and squash them.

# Screenshots (If appropriate)

# Please check this Checklist before you submit your PR:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

2022-12-09 14:30 UTC, Julienish14 approved these changes

2022-12-09 14:30 UTC, alaintresor approved these changes

2022-12-09 14:42 UTC, Francoise02 approved these changes

2022-12-09 15:30 UTC, ceelogre requested changes
Once you are on the cohort list page, add a column that shows a number of teams in each cohort. Once a user clicks on this number, it should show the teams' names in a new modal.

<img width="854" alt="image" src="https://user-images.githubusercontent.com/5022823/206736225-dd130969-6700-4021-ac47-4adb13580f1b.png">

When you are on the cohort page, once you view trainees in a particular cohort, add a field which shows the team they belong to.

<img width="854" alt="image" src="https://user-images.githubusercontent.com/5022823/206735765-dc0d920b-4208-44dc-bb6f-e74e90a74c7d.png">

2022-12-09 16:51 UTC, ishimweeli approved these changes

2022-12-13 04:54 UTC, Himbaza123h approved these changes

2022-12-13 05:06 UTC, Himbaza123h reviewed
Why am I not able to proceed with organization?
<img width="1440" alt="Screen Shot 2022-12-13 at 07 04 25" src="https://user-images.githubusercontent.com/100874204/207231299-78cbb304-3447-47b8-903e-9ddc13d82c68.png">

2022-12-13 07:51 UTC, alicepretty approved these changes

2022-12-13 09:43 UTC, ceelogre approved these changes

2022-12-13 09:44 UTC, merged