Fix organisation data scoping
atlp-rwanda/atlp-pulse-fn pull request #199
Opened 2022-12-15 12:45 UTC by Julienish14

# PR Description

This pull request fix the organisation data scoping

# Description of tasks that were expected to be completed

List all the tasks and sub-tasks that were assigned to you or that you assigned yourself. Make sure you check evey completed task.

# How has this been tested?

Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

# Number of Commits

The number of commits should not exceed **2 commits**. In case they are more than that, please take your time and squash them.

# Screenshots (If appropriate)

# Please check this Checklist before you submit your PR:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

2022-12-19 15:37 UTC, ishimweeli approved these changes

2022-12-20 14:14 UTC, ceelogre requested changes
`coordinator@devpulse.co` appears as a cohort coordinator in Org 2 yet they don't appear on the list of users in the org `Roles and Access` section.

2022-12-21 11:26 UTC, Placide123 approved these changes

2022-12-21 11:32 UTC, Julienish14 commented
> Details

Done! 
Now everything is fine

2022-12-21 11:33 UTC, Placide123 approved these changes

2022-12-21 13:53 UTC, alaintresor approved these changes

2022-12-21 14:58 UTC, ceelogre approved these changes

2022-12-21 14:58 UTC, merged