Add coordinators page
atlp-rwanda/atlp-pulse-fn pull request #208
Opened 2023-06-12 14:04 UTC by fabrice-rw

# PR Description

This pull request adds a coordinators page that displays a list of coordinators and allows users to add new coordinators.

# Description of tasks that were expected to be completed

- [x] Task 1: Implement the coordinators page component
- [x] Task 2: Style the coordinators page to match the Trainee's page
- [x] Task 3: Create a button to add new coordinators
- [x] Task 4: Handle the addition of new coordinators
- [x] Task 5: Fetch and display the list of coordinators from the backend

# How has this been tested?

I have tested the functionality of the coordinators page by performing the following steps:

1. Navigated to the coordinators page
2. Verified that the list of coordinators is displayed correctly
3. Clicked the "Add Coordinator" button and confirmed that the form for adding a coordinator appears
4. Entered valid information in the form and submitted it
5. Verified that the new coordinator is added to the list and displayed correctly

Test Configuration:
- Operating System: Windows 10
- Browser: Google Chrome (Version 90.0.4430.212)

# Number of Commits

This pull request consists of 1 commit.

2023-06-27 13:35 UTC, teerenzo requested changes
do rebase

2023-06-27 14:15 UTC, teerenzo approved these changes

2023-06-27 18:13 UTC, Marthatwesi approved these changes

2023-06-28 08:31 UTC, ceelogre requested changes
I'm unable to login
<img width="482" alt="image" src="https://github.com/atlp-rwanda/atlp-pulse-fn/assets/5022823/4c794d25-d636-4424-920f-302281168981">

2023-06-28 17:33 UTC, ceelogre approved these changes

2023-06-28 17:33 UTC, merged