Add toast on deleting cohort
atlp-rwanda/atlp-pulse-fn pull request #210
Opened 2023-06-13 14:45 UTC by Fidela1

# PR Description

This PR add toast on delete cohort and add loading on delete buttons

# Description of tasks that were expected to be completed

- [x] Add toast on deleting cohort
- [x] Add loading on delete button

# How has this been tested?

Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

# Number of Commits

The number of commits should not exceed **2 commits**. In case they are more than that, please take your time and squash them.

# Screenshots (If appropriate)

# Please check this Checklist before you submit your PR:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

2023-06-14 14:30 UTC, teerenzo requested changes
I can't login, make sure that we are able to login

2023-06-14 15:16 UTC, UwaweTera approved these changes

2023-06-14 15:35 UTC, UwaweTera reviewed
Fidela try to use remote URL for metron in this PR

2023-06-14 15:46 UTC, UwaweTera requested changes
Fidela try to use remote URL for metron in this PR

2023-06-14 18:31 UTC, Munezeroolivierhugue requested changes
fidela try to give a description of how to test it because go to cohort page is challenging

2023-06-15 10:24 UTC, teerenzo approved these changes

2023-06-19 07:37 UTC, ceelogre approved these changes

2023-06-19 07:49 UTC, UwaweTera approved these changes

2023-06-19 14:11 UTC, Munezeroolivierhugue approved these changes

2023-06-21 09:31 UTC, ceelogre requested changes

2023-06-21 09:31 UTC, ceelogre commented on src/containers/admin-dashBoard/DeleteCohortModal.tsx
> +      toast.success("Cohort deleted successfully");
Message should be translated.

2023-06-23 10:51 UTC, merged