organisation crud
atlp-rwanda/atlp-pulse-fn pull request #213
Opened 2023-06-21 16:39 UTC by teerenzo

# PR Description

# Description of tasks that were expected to be completed

List all the tasks and sub-tasks that were assigned to you or that you assigned yourself. Make sure you check evey completed task.

# How has this been tested?

Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

# Number of Commits

The number of commits should not exceed **2 commits**. In case they are more than that, please take your time and squash them.

# Screenshots (If appropriate)

# Please check this Checklist before you submit your PR:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

2023-06-22 16:08 UTC, UwaweTera approved these changes

2023-06-23 12:22 UTC, Marthatwesi approved these changes

2023-06-23 17:41 UTC, ceelogre requested changes
Can I delete an org?

2023-06-26 12:28 UTC, ceelogre approved these changes

2023-06-26 12:30 UTC, merged