ft: test setup and coverage raising.
atlp-rwanda/atlp-pulse-fn pull request #214
Opened 2023-06-22 12:49 UTC by ISHIMWE-Aime

# PR Description
We have to raise existing  test coverage and and fix build test.
Please include a brief description of the pull request you want to raise.

# Description of tasks that were expected to be completed
Our builds are failing. Coverage has dropped due to un-tested components. Let’s get our coverage up again.

List all the tasks and sub-tasks that were assigned to you or that you assigned yourself. Make sure you check evey completed task.

# How has this been tested?

Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
[Build test are passing](url)?
[Coverage has increased](url)?

# Number of Commits
1 commit

The number of commits should not exceed **2 commits**. In case they are more than that, please take your time and squash them.

# Screenshots (If appropriate)

# Please check this Checklist before you submit your PR:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

2023-06-26 12:46 UTC, teerenzo requested changes
please rebase

2023-06-29 13:26 UTC, teerenzo approved these changes

2023-06-29 13:32 UTC, fabrice-rw approved these changes

2023-06-29 16:01 UTC, ceelogre requested changes
Let's first understand why tests are not passing locally.

2023-06-30 08:06 UTC, ceelogre approved these changes

2023-06-30 08:07 UTC, merged