ft: add and update ratings
atlp-rwanda/atlp-pulse-fn pull request #218
Opened 2023-06-30 09:17 UTC by blackd44

# PR Description

We have to make sure that the coordinator can add a review and can update it.

# Description of tasks that were expected to be completed

- [ ] Coordinator add rating to a trainer
- [ ] Coordinator update rating of a trainer
- [ ] Viewing ratings

# How has this been tested?
* For unity nesting, run `npm test` command to test
* For verifying the functionality
   ```bash
    git clone https://github.com/atlp-rwanda/atlp-pulse-fn
    cd atlp-pulse-fn
    ```
    go to the branch called `ft-add-ratings` then
    ```bash
     npm install
     npm run dev
     open http://localhost:3000
    ```

# Number of Commits

**1 commit**

# Screenshots (If appropriate)
<img width="1440" alt="Screenshot 2023-06-30 at 11 01 59" src="https://github.com/atlp-rwanda/atlp-pulse-fn/assets/112763782/66f4d8c9-f5d1-4c6a-992b-e433fa12ca40">
<img width="986" alt="Screenshot 2023-06-30 at 11 02 54" src="https://github.com/atlp-rwanda/atlp-pulse-fn/assets/112763782/3474cedc-c3dd-44a0-b07e-efe62b447500">
<img width="880" alt="Screenshot 2023-06-30 at 11 17 38" src="https://github.com/atlp-rwanda/atlp-pulse-fn/assets/112763782/a5cacb1a-8ed0-472c-9ef0-c6888946ac23">

# Please check this Checklist before you submit your PR:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

2023-07-13 11:22 UTC, UwaweTera approved these changes

2023-07-13 16:20 UTC, Patienceineza approved these changes
LGTM

2023-07-13 16:32 UTC, edwinnambaje approved these changes

2023-07-14 08:39 UTC, ceelogre requested changes
When we type a feedback message, it does not appear in the box. Also, let's add a title that shows who is the trainee we are giving feedback.
![image](https://github.com/atlp-rwanda/atlp-pulse-fn/assets/5022823/023e12e9-e5ec-4684-9703-b22837a277b8)

A message that a rating has been updated is shown while the admin hasn't approved it. A better message like "waiting for admin approval" would be suited.
![image](https://github.com/atlp-rwanda/atlp-pulse-fn/assets/5022823/9d256c4e-55d1-4e9c-8f64-65ef8c776ccf)

2023-07-16 07:45 UTC, blackd44 commented
> When we type a feedback message, it does not appear in the box. Also, let's add a title that shows who is the trainee we are giving feedback. ![image](https://user-images.githubusercontent.com/5022823/253520322-023e12e9-e5ec-4684-9703-b22837a277b8.png)
> 
> A message that a rating has been updated is shown while the admin hasn't approved it. A better message like "waiting for admin approval" would be suited. ![image](https://user-images.githubusercontent.com/5022823/253518800-9d256c4e-55d1-4e9c-8f64-65ef8c776ccf.png)

the reason it wasn't working it's because there wasn't environment variable of `WS_BACKEND_URL`

2023-07-17 15:30 UTC, ceelogre approved these changes

2023-07-17 15:30 UTC, merged