implement the help-page
atlp-rwanda/atlp-pulse-fn pull request #224
Opened 2023-07-05 14:23 UTC by Mystica52

# PR description
PR used creating a help page for the use for the asking the support or feedback
implementation of the help page so that it can help the use to raise the issue and feedback

# Description of tasks that were expected to be completed

- [ ] design of the help page

- [ ] Submitting it should open a ticket in superadmin account

- [ ] superadmin menu has a tickets item

- [ ] Tickets appear on the dashboard

- [ ] Notifications are sent for you new tickets

# How has this been tested?
`/dashbord/support`
- write a message to supper admin
- superadmin get the notification of that tickets

# Number of Commits

# Screenshots (If appropriate)

# Please check this Checklist before you submit your PR:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

2023-07-08 18:03 UTC, AbdulKhaliq59 reviewed
I am just getting this error `Continue seeing toastify notification after already sent message`.
I used to resent a message while I am typing that message, I was continue getting notification.
<img width="1440" alt="Screenshot 2023-07-08 at 20 02 08" src="https://github.com/atlp-rwanda/atlp-pulse-fn/assets/71641626/51e23212-fb39-44b7-8ed8-a0995fc7decc">
I am not even get access on `open button` when help message received it,
<img width="1440" alt="Screenshot 2023-07-08 at 20 03 00" src="https://github.com/atlp-rwanda/atlp-pulse-fn/assets/71641626/fc6fb9e2-3dec-4ae7-b8d2-c0b7401ebbb4">
remove some `console.log` on backend if it is possible

2023-07-10 13:23 UTC, ceelogre requested changes, later dismissed
When typing in dark mode, one is unable to see the characters.

![image](https://github.com/atlp-rwanda/atlp-pulse-fn/assets/5022823/7a06cf1c-9424-48e9-8d89-647627b06711)

After submitting a ticket, there's no feedback to the user (no modal or any other reaction that they have submitted a ticket).

What are the credentials to login as superadmin? You only mentioned "login as superadmin" in PR description.
![image](https://github.com/atlp-rwanda/atlp-pulse-fn/assets/5022823/8c312c5c-22f4-4280-8caa-c2e16cc82796)

Upon successful submission , there's a user toast notification

2023-07-11 07:16 UTC, oliviertech212 submitted a review, later dismissed
clear form after sending

2023-07-11 17:32 UTC, oliviertech212 approved these changes

2023-07-11 21:53 UTC, ceelogre requested changes
Add timestamps in human readable format (an hour ago, today, 2 weeks ago, ...)

![image](https://github.com/atlp-rwanda/atlp-pulse-fn/assets/5022823/d416736d-d45a-4e91-a820-64c90fa22d28)

2023-07-12 12:42 UTC, ceelogre commented
When you open the notification, it takes you to the rating page (https://metron-devpulse-6yft9s5mz-metron.vercel.app/dashboard/ratings) which is not what we want.

2023-07-12 12:45 UTC, ceelogre requested changes, later dismissed

2023-07-12 12:45 UTC, ceelogre commented on src/utils/timePassedFormating.ts
> +import moment from 'moment';
Moment is no longer maintained. See: https://momentjs.com/docs/#/-project-status/

2023-07-13 09:24 UTC, ceelogre commented on src/queries/helps.queries.tsx
> +export default GET_HELPS;
Helps should be renamed to tickets.

2023-07-13 11:54 UTC, ceelogre approved these changes

2023-07-13 11:54 UTC, ceelogre approved these changes

2023-07-13 11:57 UTC, fabrice-rw approved these changes

2023-07-13 11:58 UTC, merged