# user be able to see login activities
atlp-rwanda/atlp-pulse-fn pull request #232
Opened 2023-07-16 14:43 UTC by Martha-Iradukunda

# PR Description
Please include a brief description of the pull request you want to raise.
* Implement login activity tracking and email notifications for unusual login attempts.

# Description of tasks that were expected to be completed
List all the tasks and sub-tasks that were assigned to you or that you assigned yourself. Make sure you check evey completed task.

# How has this been tested?

Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

# Number of Commits

The number of commits should not exceed **2 commits**. In case they are more than that, please take your time and squash them.

# Screenshots (If appropriate)
![Screenshot from 2023-07-16 17-28-28](https://github.com/atlp-rwanda/atlp-pulse-fn/assets/101427855/04966d04-cebd-4b5b-9c9c-b29c9b4eec55)

# Please check this Checklist before you submit your PR:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

2023-07-17 17:54 UTC, blackd44 approved these changes

2023-07-18 09:16 UTC, Habihirwe approved these changes
LGMT

2023-07-19 07:50 UTC, Marthatwesi approved these changes

2023-07-19 08:01 UTC, Fidela1 approved these changes

2023-07-19 14:09 UTC, ceelogre requested changes
I'm unable to view the component.
The url seems to go through dashboard (https://metron-devpulse-kjkgzdekz-metron.vercel.app/dashboard/loginActivities) I'm not sure why, could you explain more?
Also, the list item should come before `Logout`
![image](https://github.com/atlp-rwanda/atlp-pulse-fn/assets/5022823/19d1b6bb-47ab-4dd8-8af8-04c55f03081e)

2023-07-28 15:05 UTC, ceelogre approved these changes

2023-07-28 15:08 UTC, merged