redesign all components using new theme
atlp-rwanda/atlp-pulse-fn pull request #243
Opened 2023-07-24 11:32 UTC by Fidela1

# PR Description
New UI implementation

# Description of tasks that were expected to be completed

- [x] Theme is applied across all existing pages/components
- [ ] Landing page is implemented in light theme

# How has this been tested?

- Checkout to branch ft-create-dashboard cards
- login as a coordinator or an admin
- Check UI implementation

# Screenshots (If appropriate)

# Please check this Checklist before you submit your PR:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

2023-07-28 13:06 UTC, ISHIMWE-Aime requested changes
Thank you for the work you have done so far; but, there are still many rooms for improvement.

1. On welcoming message and Join Us button the alignment, font-family, font-weight, font-size used in implementation is not making your implementation look similar to the design.
2. Excluding "Performance Management/Analytics" section, on other sections, re-think about the card width size and illustration width size you used for matching them with design.
3. On this tittle "Excellent human resources and companies come shape the future together", only the first sentence "Excellent human resources and companies" is in italic but the rest portion is not italic.
4. Testimonial card height is the same on design, try to the same.
5. Finally, add font-family, font-weight, font-size on your implementation as used in design.

Thank you again for the work you have done so far.

2023-08-01 08:15 UTC, ISHIMWE-Aime commented
Good morning @Fidela1,
I have made review of your work you've done so far on home page design; thank you for trying to work according to the changes I have requested, yet there is still many rooms for changes according to the changes I had requested previously.
Thank you and nice day.
Happy coding.

2023-08-03 13:08 UTC, chrill-christella approved these changes

2023-08-03 15:04 UTC, ISHIMWE-Aime approved these changes
LGTM

2023-08-03 15:06 UTC, ceelogre approved these changes

2023-08-03 15:06 UTC, merged