ft:Upload Profile
atlp-rwanda/atlp-pulse-fn pull request #244
Opened 2023-07-24 12:54 UTC by patsicko

# PR Description

- As a trainee, I want to be able to upload my resume into the system.

# Description of tasks that were expected to be completed

- Resume documents can be uploaded to the servers
- External links (e.g. to google drive) can also be added
- Coordinators and admin can view each trainee's resume

# How has this been tested?
- Clone the repo
- Checkout into `` ft-upload-resume ``  branch
- run  `` npm i ``
- Navigate to the local url on the browser
- Login as a normal user
- Click on profile icon on top right corner
- Click on Profile
- Click on Edit Profile
- Click on Upload resume, a panel containing to buttons will be displayed. 1. Upload: This is for upload resume from your local pc, 2. Add external link: This is for adding resume from external link
- Submit the resume

# Number of Commits
1
The number of commits should not exceed **2 commits**. In case they are more than that, please take your time and squash them.

# Screenshots (If appropriate)

# Please check this Checklist before you submit your PR:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

2023-08-10 14:14 UTC, oliviertech212 requested changes
rebase from develop
![image](https://github.com/atlp-rwanda/atlp-pulse-fn/assets/89464364/c9ccc1fa-d151-449a-a8d4-5661346ccd2a)

2023-08-11 10:49 UTC, oliviertech212 approved these changes

2023-08-11 14:27 UTC, AbdulKhaliq59 approved these changes
LGTM

2023-08-11 17:15 UTC, ceelogre requested changes
I don't see an option to upload documents on profile.
<img width="1393" alt="image" src="https://github.com/atlp-rwanda/atlp-pulse-fn/assets/5022823/b55138ff-77d3-4bb5-9d2c-e83ed7ab3ecf">

2023-08-11 18:03 UTC, Luciefifi approved these changes

2023-08-18 10:29 UTC, ceelogre approved these changes

2023-08-18 10:33 UTC, ceelogre approved these changes

2023-08-18 10:33 UTC, merged