Ft(export ratings)
atlp-rwanda/atlp-pulse-fn pull request #247
Opened 2023-07-28 07:43 UTC by chrill-christella

# PR Description

implement exporting data to CSV/Excel for the admin and the coordinator

# How will it be tested?

checkout to ft-exporting-data branch
npm i
npm run dev
login as an admin or a coordinator
navigate to ratings
please make sure that you have ratings on the performance ratings table
click on export data button to export the over-all ratings of the trainnes

# Screenshots (If appropriate)

        
<img width="1181" alt="Screenshot 2023-07-28 at 09 33 57" src="https://github.com/atlp-rwanda/atlp-pulse-fn/assets/87751814/1016d51b-ebde-4bbb-ad0e-d58ddca61ab
<img width="1440" alt="Screenshot 2023-07-28 at 09 40 01" src="https://github.com/atlp-rwanda/atlp-pulse-fn/assets/87751814/2ee9f73e-02a9-4de2-ad06-dae2cf3787a1">
5">

2023-08-03 11:32 UTC, Martha-Iradukunda approved these changes
LGTM

2023-08-07 12:57 UTC, Luciefifi approved these changes

2023-08-11 13:55 UTC, ericndungutse requested changes
**You need validation to deny user from submitting ratings when no trainee is selected.**
![Screenshot (43)](https://github.com/atlp-rwanda/atlp-pulse-fn/assets/55640083/33ee68ca-1433-4b2c-945d-7997cbd4d510)

**Can you round off average**
![Screenshot (44)](https://github.com/atlp-rwanda/atlp-pulse-fn/assets/55640083/1d2762cc-cbb1-4d71-b571-05d2a15187e2)

2023-08-14 16:50 UTC, ceelogre commented
Putting this on hold as I cannot add a trainee to a cohort so as to rate hence no export data.
![image](https://github.com/atlp-rwanda/atlp-pulse-fn/assets/5022823/c84d1eef-1b2e-44ee-a142-bf22ed3390ad)

2023-08-18 08:46 UTC, ericndungutse approved these changes

2023-08-18 10:57 UTC, ceelogre approved these changes

2023-08-18 10:58 UTC, merged