feature:redesigned help page
atlp-rwanda/atlp-pulse-fn pull request #250
Opened 2023-08-01 18:24 UTC by oliviertech212

# PR Description
 redesign help page component.

# Description of tasks that were expected to be completed

- change new theme
- redesign tickets card

# How has this been tested?

- clone the repo
- checkout to ft-redesigned-help-page
-  login navigate to Help then send a request
- once the request is sent  navigate to  Tickets

# Screenshots (If appropriate)
![image](https://github.com/atlp-rwanda/atlp-pulse-fn/assets/89464364/bf7e3b81-0eac-493a-91ae-40bf1b0e8b6f)

2023-08-03 17:17 UTC, ericndungutse approved these changes

2023-08-04 07:55 UTC, Mystica52 approved these changes
it is working as expected  and it  looks better

2023-08-04 12:32 UTC, ceelogre requested changes
Let's first talk to the design team. The current UI can be improved.

2023-08-04 13:10 UTC, Munezeroolivierhugue approved these changes

2023-08-07 12:35 UTC, ngoma3 approved these changes

2023-08-09 09:52 UTC, ceelogre requested changes
Why does it look like you've not fully rebased? This is not how the stable login page should look.
<img width="655" alt="image" src="https://github.com/atlp-rwanda/atlp-pulse-fn/assets/5022823/29467503-ddee-47f3-8dcb-8f9f903083c4">

The row after content is not properly aligned.
<img width="655" alt="image" src="https://github.com/atlp-rwanda/atlp-pulse-fn/assets/5022823/fb308fc7-27c0-4008-9143-1568eb2a80e5">

2023-08-09 14:00 UTC, ceelogre approved these changes

2023-08-09 14:01 UTC, merged