Ft docs implementation
atlp-rwanda/atlp-pulse-fn pull request #254
Opened 2023-08-08 08:01 UTC by teerenzo

# PR Description

Please include a brief description of the pull request you want to raise.

# Description of tasks that were expected to be completed

List all the tasks and sub-tasks that were assigned to you or that you assigned yourself. Make sure you check evey completed task.

# How has this been tested?

Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

# Number of Commits

The number of commits should not exceed **2 commits**. In case they are more than that, please take your time and squash them.

# Screenshots (If appropriate)

# Please check this Checklist before you submit your PR:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

2023-08-14 13:20 UTC, patsicko approved these changes

2023-08-14 13:38 UTC, Habihirwe approved these changes
LGMT

2023-08-14 17:51 UTC, ceelogre requested changes
Let's use URLs in this style.
https://metron-devpulse-neihqjzh1-metron.vercel.app/docs/admin

2023-08-16 08:42 UTC, ceelogre commented
Items should be in a table.
![image](https://github.com/atlp-rwanda/atlp-pulse-fn/assets/5022823/9445e99b-bb2b-471c-a5bf-e0746154dc63)

2023-08-17 10:57 UTC, ceelogre approved these changes

2023-08-17 10:57 UTC, merged