Home Page Documentation
atlp-rwanda/atlp-pulse-fn pull request #255
Opened 2023-08-08 12:37 UTC by Marthatwesi

# PR Description

Please include a brief description of the pull request you want to raise.

# Description of tasks that were expected to be completed

List all the tasks and sub-tasks that were assigned to you or that you assigned yourself. Make sure you check evey completed task.

# How has this been tested?

Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

# Number of Commits

The number of commits should not exceed **2 commits**. In case they are more than that, please take your time and squash them.

# Screenshots (If appropriate)

# Please check this Checklist before you submit your PR:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

2023-08-08 14:04 UTC, UwaweTera approved these changes

2023-08-09 10:30 UTC, teerenzo approved these changes

2023-08-09 12:57 UTC, chrill-christella approved these changes

2023-08-11 17:32 UTC, ceelogre requested changes
Take a look at the layout [here](https://redux.js.org/introduction/getting-started) for inspiration on how to structure the content on this page.

2023-08-14 11:20 UTC, ceelogre commented
This container is not necessary. The content on it should go under sub list items in left panel.
<img width="1067" alt="image" src="https://github.com/atlp-rwanda/atlp-pulse-fn/assets/5022823/540db6bb-73ca-49cd-a1b0-0c359dcd2a58">

2023-08-24 20:12 UTC, ceelogre commented
The previous issue is messed up but now the right section is now messed up.
<img width="1260" alt="image" src="https://github.com/atlp-rwanda/atlp-pulse-fn/assets/5022823/8dac7c99-755c-4399-9bbc-59ff5b26a624">

2023-08-25 07:51 UTC, ceelogre approved these changes

2023-08-25 07:51 UTC, merged