mobile view of homepage
atlp-rwanda/atlp-pulse-fn pull request #257
Opened 2023-08-10 08:36 UTC by Fidela1

# PR Description

Implement mobile view and header on homepage

# Description of tasks that were expected to be completed

- [x] Working on mobile view

# How has this been tested?

Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

# Number of Commits

The number of commits should not exceed **2 commits**. In case they are more than that, please take your time and squash them.

# Screenshots (If appropriate)

# Please check this Checklist before you submit your PR:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

2023-08-10 13:05 UTC, ngoma3 submitted a review, later dismissed
Hey, some texts are not clear in the dark mode

2023-08-10 13:39 UTC, chrill-christella approved these changes

2023-08-10 22:08 UTC, ceelogre requested changes
Clicking on About takes you to a page that has the old image with a 404 text. Is this on purpose?
<img width="965" alt="image" src="https://github.com/atlp-rwanda/atlp-pulse-fn/assets/5022823/d4f794e4-2c7b-4d38-ac2e-763d99ed1e30">

On iPhone 11 pro max, the image is not loaded. Take a look at the screenshot below.
![mobile](https://github.com/atlp-rwanda/atlp-pulse-fn/assets/5022823/fdc2e21f-8ef0-4501-a2d1-7afe4f8c669c)

2023-08-11 09:19 UTC, ericndungutse approved these changes

2023-08-14 17:51 UTC, ceelogre approved these changes

2023-08-14 17:51 UTC, merged