Ch 59 dark theme implementation
atlp-rwanda/atlp-pulse-fn pull request #259
Opened 2023-08-10 17:54 UTC by Mystica52

# PR Description
PR is used to implement dark theme 

# Description of tasks that were expected to be completed

- Dark theme is added using our new design

# How has this been tested?
**for local**
clone the github
run `npm install`
run `npm run dev`
then on hope page header there is moon icon  click on it 
change it sun icon and look at on the whole page
**on deploy version** 
- look at  home page 
- there is moon icon  click on it 
- change it sun icon and look at on the whole page

# Number of Commits
1 commit

# Screenshots (If appropriate)

# Please check this Checklist before you submit your PR:

- [ ] Dark theme is added using our new design

2023-08-16 18:00 UTC, oliviertech212 approved these changes

2023-08-16 18:22 UTC, ericndungutse approved these changes
LGTM

2023-08-16 18:38 UTC, chrill-christella approved these changes

2023-08-16 19:33 UTC, ceelogre requested changes
**Use private mode to test this:** 
When you login in a browser that has dark mode preference, the theme is picked up but when you go Preferences under profile, the option is still `Light theme`
![image](https://github.com/atlp-rwanda/atlp-pulse-fn/assets/5022823/d06a6838-4101-45b8-af18-3df894cb609f)

The box on the left is white.
![image](https://github.com/atlp-rwanda/atlp-pulse-fn/assets/5022823/3fdb967f-aa31-456d-83e3-ec0453ebe383)

2023-08-17 06:31 UTC, ISHIMWE-Aime commented
@Mystica52 Have you addressed the changes @ceelogre requested?

2023-08-18 11:44 UTC, ceelogre approved these changes

2023-08-18 11:45 UTC, merged