add orgLogin update
atlp-rwanda/atlp-pulse-fn pull request #260
Opened 2023-08-11 10:42 UTC by rachelumwari

# PR Description

This PR add new changes on Sign in to your Organization

# Screenshots (If appropriate)
![image](https://github.com/atlp-rwanda/atlp-pulse-fn/assets/94528079/863742bd-b9e3-4c11-bb2e-3963b2e87adb)

2023-08-11 10:44 UTC, ngoma3 approved these changes

2023-08-14 10:32 UTC, ngoma3 approved these changes

2023-08-14 15:11 UTC, patsicko approved these changes

2023-08-14 18:38 UTC, ceelogre requested changes
The space on `your-organization` is big. Can we re-create an effect like this?
https://github.com/atlp-rwanda/atlp-pulse-fn/assets/5022823/0f967848-f208-4344-a0dd-4a9d97c90728

2023-08-14 18:42 UTC, ceelogre commented on package.json
> +    "dev2": "webpack server",
Why the use of `dev2` ?

2023-08-16 16:36 UTC, ceelogre approved these changes

2023-08-16 16:37 UTC, merged