Ft team details
atlp-rwanda/atlp-pulse-fn pull request #264
Opened 2023-08-15 06:30 UTC by chrill-christella

# PR Description

team details implementation

### Description of tasks that were expected to be completed

-  coordinator and manager are able to see  team details

### How to test this PR?

- login as a` manager` or a `coordinator `
- please make sure that you have members in the team and also ratings to have a clear view of all corresponding components
- navigate to teams in the sidebar or dashboard for the manager
- click on team card and you will be able to see all details about the team

2023-08-31 14:11 UTC, oliviertech212 requested changes
cards need to be centered  
![image](https://github.com/atlp-rwanda/atlp-pulse-fn/assets/89464364/9190cd00-9a0a-4d8b-a36e-fa0ac0f3963d)
And also this need to be fixed 
![image](https://github.com/atlp-rwanda/atlp-pulse-fn/assets/89464364/07a0c669-03b9-46d7-9dc3-cb12d375fcbf)

2023-09-07 09:16 UTC, Luciefifi approved these changes

2023-09-09 04:55 UTC, Martha-Iradukunda approved these changes

2023-09-10 03:27 UTC, oliviertech212 approved these changes

2023-09-11 08:34 UTC, Aline096 approved these changes

2023-09-15 08:58 UTC, ceelogre reviewed
Why is that in team II `Active` shows 1 but on opening it, there's no one.
![image](https://github.com/atlp-rwanda/atlp-pulse-fn/assets/5022823/bb572052-0547-46d6-a47e-d4f798187c1c)

2023-09-15 12:22 UTC, merged