Rating Feature Implementation
atlp-rwanda/atlp-pulse-fn pull request #265
Opened 2023-08-15 10:13 UTC by Aline096

# PR Description

Rating Feature Implementation

# Description of tasks that were expected to be completed

- [ ] View weekly ratings for active trainee
- [ ] View weekly ratings for dropped trainee
- [ ] Add new rating 

# Screenshots (If appropriate)

2023-08-25 07:23 UTC, Martha-Iradukunda approved these changes

2023-08-29 09:47 UTC, edwinnambaje approved these changes

2023-08-29 10:05 UTC, chrill-christella approved these changes

2023-09-05 16:54 UTC, ceelogre requested changes
There is no button to add new ratings for a new trainee added to a team. Also, the `no-trainee data available` window is not uniform for all trainees.
<img width="774" alt="image" src="https://github.com/atlp-rwanda/atlp-pulse-fn/assets/5022823/d33dd4e0-dba2-4685-9044-7e8cc4553b55">
<img width="774" alt="image" src="https://github.com/atlp-rwanda/atlp-pulse-fn/assets/5022823/9cab0184-71f4-42ba-bcf5-426e65abca73">

2023-09-11 08:35 UTC, ceelogre commented
Add the name of the sprint currently being rated.
<img width="540" alt="image" src="https://github.com/atlp-rwanda/atlp-pulse-fn/assets/5022823/d3b3e889-1f7d-4dca-be83-b02b99158359">

2023-09-11 19:14 UTC, ceelogre approved these changes

2023-09-11 19:14 UTC, merged