bg-login-error-message
atlp-rwanda/atlp-pulse-fn pull request #267
Opened 2023-08-17 11:26 UTC by teerenzo

# PR Description

Please include a brief description of the pull request you want to raise.

# Description of tasks that were expected to be completed

List all the tasks and sub-tasks that were assigned to you or that you assigned yourself. Make sure you check evey completed task.

# How has this been tested?

Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

# Number of Commits

The number of commits should not exceed **2 commits**. In case they are more than that, please take your time and squash them.

# Screenshots (If appropriate)

# Please check this Checklist before you submit your PR:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

2023-08-17 12:13 UTC, patsicko approved these changes

2023-08-17 12:13 UTC, rachelumwari approved these changes

2023-08-17 13:45 UTC, ceelogre requested changes

2023-08-17 13:45 UTC, ceelogre commented on src/pages/AdminTraineeDashboard.tsx
> +    console.log(filteredUser[0].profile?.githubUsername);
No log messages.

2023-08-17 20:53 UTC, ceelogre commented
When the language is set to french, the message re-appears.
<img width="801" alt="image" src="https://github.com/atlp-rwanda/atlp-pulse-fn/assets/5022823/c4853856-cafb-4b4c-ae8a-7f2e4987855b">

2023-08-18 08:24 UTC, ceelogre approved these changes

2023-08-18 08:24 UTC, merged