Email templates
atlp-rwanda/atlp-pulse-fn pull request #278
Opened 2023-08-29 14:57 UTC by Habihirwe

# PR Description

This PR updates the email templates.

# Description of tasks that were expected to be completed

- [x] Update the invitation email template to match the required.
- [x] Make sure all the link and redirections uses the correct urls.

# How has this been tested?

1. Login as the admin and navigate to the trainees tab.
2. click the invite user button and insert the email of the trainee to be invited.
3. Lastly, check the email you provide on step 2 for the update template.

# Number of Commits

1

# Screenshots (If appropriate)

# Please check this Checklist before you submit your PR:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

2023-09-05 16:15 UTC, ceelogre requested changes
The last two should be fixed to match the first.
![image](https://github.com/atlp-rwanda/atlp-pulse-fn/assets/5022823/cf4222c4-fba5-47ee-9c81-1d512c41b7d4)

2023-09-08 09:07 UTC, edwinnambaje approved these changes

2023-09-09 10:55 UTC, Martha-Iradukunda approved these changes

2023-09-10 09:48 UTC, AbdulKhaliq59 approved these changes
Rebase unless it LGTM

2023-09-11 08:04 UTC, patsicko approved these changes

2023-09-11 08:58 UTC, Luciefifi approved these changes

2023-09-13 15:07 UTC, ceelogre approved these changes

2023-09-13 15:07 UTC, merged