#DP-9 ft: Admin dashboard
atlp-rwanda/atlp-pulse-fn pull request #28
Opened 2022-07-14 11:11 UTC by jeandamascyifuzo

### PR Description
This Pr shows the progress of the Admin dashboard. 

### Description of the tasks to be completed
- [ ] Add and remove user emails
- [x] Add and remove programs/cohorts
- [ ] Add and remove session for attendance
- [ ] Manage roles

### How has this been tested?
clone Rep
git checkout ft-admin-dashboard-dp-9
git fetch
npm install
npm run dev

### Relevant trello story:
[Trello](https://trello.com/c/KCXhcD9T/9-admin-dashboard)

2022-07-14 11:13 UTC, feyton commented
I deployed a review app for you to try out this pull request 👇🏽

Heroku App: https://devpulse-review-app-28.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

2022-07-18 06:38 UTC, chanceDira reviewed
Good work, 

On my end am getting margin bottom issue

<img width="1440" alt="Screen Shot 2022-07-18 at 08 36 11" src="https://user-images.githubusercontent.com/67952319/179456740-6262b8a3-245a-401b-be8b-7970a6d6cff2.png">

2022-07-18 08:53 UTC, samyshyaka requested changes
Nice work @jeandamascyifuzo ,

- Try to center your cards
- Remember to put drop-downs where they are missing

2022-07-18 08:53 UTC, samyshyaka commented on src/App.tsx
> +      {/* <Dash/> */}
You can remove the commented code

2022-07-18 08:53 UTC, samyshyaka commented on src/containers/admin-dashBoard/Cohorts.tsx
> +                                                        ...
Remember to include the dropdown for actions

2022-07-19 13:55 UTC, chanceDira approved these changes

2022-07-20 06:56 UTC, samyshyaka requested changes
Find out why the builds are failing and try to fix them

2022-07-20 09:47 UTC, Julesbi approved these changes

2022-07-20 10:55 UTC, IIshimwe approved these changes

2022-07-20 12:40 UTC, ceelogre reviewed
Coverage is very low.

2022-07-21 15:21 UTC, ceelogre reviewed
What's the URL to test this?

2022-07-21 16:13 UTC, ceelogre requested changes
The elements are not aligned on the left. Also, you don't need to translate certain words like `cohorte` and `concept de base`
![Capture d’écran 2022-07-21 à 17 44 24](https://user-images.githubusercontent.com/5022823/180261260-0d735565-c41c-45d3-b7bf-4f5898a92bc7.png)

2022-07-22 06:03 UTC, samyshyaka approved these changes

2022-07-22 06:09 UTC, ceelogre approved these changes

2022-07-22 06:09 UTC, merged