Feat(drop trainee): Admin/coordinator to drop trainee
atlp-rwanda/atlp-pulse-fn pull request #281
Opened 2023-09-05 07:20 UTC by Martha-Iradukunda

# PR Description

Please include a brief description of the pull request you want to raise.

# Description of tasks that were expected to be completed

List all the tasks and sub-tasks that were assigned to you or that you assigned yourself. Make sure you check evey completed task.

# How has this been tested?

Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

# Number of Commits

The number of commits should not exceed **2 commits**. In case they are more than that, please take your time and squash them.

# Screenshots (If appropriate)

# Please check this Checklist before you submit your PR:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

2023-09-13 07:11 UTC, blackd44 approved these changes

2023-09-13 07:20 UTC, Habihirwe approved these changes

2023-09-13 07:56 UTC, chrill-christella approved these changes

2023-09-13 08:16 UTC, Aline096 approved these changes

2023-09-13 15:08 UTC, edwinnambaje approved these changes

2023-09-22 09:57 UTC, ceelogre requested changes
I'm unable to rate using your PR. Could you confirm with Patrick where the problem is?
<img width="1047" alt="image" src="https://github.com/atlp-rwanda/atlp-pulse-fn/assets/5022823/56cbdf22-ee8f-4702-a1f7-8d3adf1146f8">
Also, it looks like your PR is connected to the staging db which shouldn't be the case.

2023-10-05 09:25 UTC, ceelogre commented
The drop action is still available on dropped trainees.

2023-10-12 17:38 UTC, ceelogre approved these changes

2023-10-12 17:38 UTC, merged