Add Processing State on Login Button as soon as User Clicks on it
atlp-rwanda/atlp-pulse-fn pull request #293
Opened 2023-09-10 14:15 UTC by ericndungutse

# PR Description
Thi **PR** solves processing state on **login user button**

# How has this been tested?

- Visit **deployment preview** of this **PR**
- Go to `/users/login`
- Enter **credentials**
- As soon as you click on login button, the **processing state** should be triggered imidiately

2023-09-10 18:59 UTC, oliviertech212 approved these changes

2023-09-12 12:31 UTC, edwinnambaje reviewed
<img width="1440" alt="Screenshot 2023-09-12 at 14 30 49" src="https://github.com/atlp-rwanda/atlp-pulse-fn/assets/56297754/37e1b625-c62f-43d3-83fb-0009db2b0218">
Is this supposed to have this width?

2023-09-13 14:55 UTC, Habihirwe approved these changes

2023-09-13 15:13 UTC, ericndungutse commented
> <img alt="Screenshot 2023-09-12 at 14 30 49" width="1440" src="https://user-images.githubusercontent.com/56297754/267328776-37e1b625-c62f-43d3-83fb-0009db2b0218.png"> Is this supposed to have this width?

It is better if button maintains its layout in loading state

2023-09-13 15:31 UTC, edwinnambaje approved these changes

2023-09-15 07:25 UTC, ceelogre requested changes
Rebase and reset merge commits before we proceed.
<img width="1128" alt="image" src="https://github.com/atlp-rwanda/atlp-pulse-fn/assets/5022823/3ab79ec2-8c1d-40b8-b30d-a5738e92eee4">

2023-09-15 09:27 UTC, ceelogre approved these changes

2023-09-15 09:28 UTC, merged