fixing coudinary
atlp-rwanda/atlp-pulse-fn pull request #298
Opened 2023-09-15 10:28 UTC by Muhet

# PR Description

Fixing the cloudinary issue by replacing the old account to new one 

# Description of tasks that were expected to be completed

Replacing Cloudinary account

# How has this been tested?

Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

# Number of Commits

The number of commits should not exceed **2 commits**. In case they are more than that, please take your time and squash them.

# Screenshots (If appropriate)

# Please check this Checklist before you submit your PR:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

2023-09-19 10:13 UTC, Virgile1k approved these changes, later dismissed
checked

2023-09-19 13:11 UTC, NTElissa submitted a review, later dismissed

2023-09-19 14:08 UTC, yobuir submitted a review, later dismissed

2023-09-22 12:30 UTC, Virgile1k approved these changes
checked

2023-09-28 11:20 UTC, yobuir approved these changes

2023-09-28 11:53 UTC, NTElissa approved these changes

2023-09-29 07:41 UTC, ceelogre requested changes
When a user has chosen a new profile picture, add a loading icon/skeleton to show the user that there is an ongoing activity.

2023-10-02 08:47 UTC, yobuir approved these changes

2023-10-02 12:02 UTC, ceelogre approved these changes

2023-10-02 12:03 UTC, merged