FIX(bug): A bug that causes the profile image to stay static.
atlp-rwanda/atlp-pulse-fn pull request #301
Opened 2023-09-19 15:08 UTC by madebypatrick

# PR Description
It fixes the design bugs in the admin dashboard.
# Description of tasks that were expected to be completed

- [x] It is fixing the profile image of the trainee so that it won't keep hiding the details of the trainee.
- [x] It is changing the close icon for the trainee list from the "x" letter to the universal close symbol.

# How has this been tested?

- Log in as the admin, then access the trainees' ratings and profiles to observe changes in both profile picture behavior and the design of the close button.
- Log in as the admin, then navigate to the team's model within the "Teams and Cohorts" sections in the left sidebar.

# Number of Commits

The number of commits should not exceed **2 commits**. In case they are more than that, please take your time and squash them.

# Screenshots (If appropriate)

![msedge_7zfR3kMYTD](https://github.com/atlp-rwanda/atlp-pulse-fn/assets/87605095/ba19983b-b29d-4ff2-873f-42681799393d)
![msedge_pjabCbYsYW](https://github.com/atlp-rwanda/atlp-pulse-fn/assets/87605095/e3025184-1502-4c07-9caa-6aa4585e3d69)
![msedge_uPuJKdMxjl](https://github.com/atlp-rwanda/atlp-pulse-fn/assets/87605095/52bcee0e-c621-4445-bbe2-a7dd0c098c68)

# Please check this Checklist before you submit your PR:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My code generate no warnings
- [x] My test coverage meet the set test coverage threshold
- [x] There are no vulnerabilities
- [x] There are no conflicts with the base branch

2023-09-26 05:17 UTC, Virgile1k approved these changes
Checked

2023-09-26 11:11 UTC, NTElissa approved these changes

2023-09-26 13:04 UTC, Gentille-dev approved these changes

2023-09-26 14:43 UTC, ceelogre requested changes
I'm unable to login with the usual credential.
![image](https://github.com/atlp-rwanda/atlp-pulse-fn/assets/5022823/32e4717c-267f-49f8-9b90-e093b4b4181e)

2023-09-26 15:40 UTC, madebypatrick commented
> I'm unable to login with the usual credential. ![image](https://user-images.githubusercontent.com/5022823/270695930-32e4717c-267f-49f8-9b90-e093b4b4181e.png)

Hey, you may use kylesjet1@gmail.com to log in.

2023-10-04 19:50 UTC, ceelogre approved these changes

2023-10-04 19:51 UTC, merged