Update Resume.tsx
atlp-rwanda/atlp-pulse-fn pull request #308
Opened 2023-10-02 12:23 UTC by Muhet

# PR Description

Please include a brief description of the pull request you want to raise.

# Description of tasks that were expected to be completed

List all the tasks and sub-tasks that were assigned to you or that you assigned yourself. Make sure you check evey completed task.

# How has this been tested?

Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

# Number of Commits

The number of commits should not exceed **2 commits**. In case they are more than that, please take your time and squash them.

# Screenshots (If appropriate)

# Please check this Checklist before you submit your PR:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

2023-10-03 17:09 UTC, NdatimanaSamuel approved these changes

2023-10-03 19:40 UTC, Virgile1k approved these changes
Checked and. Approved

2023-10-04 12:17 UTC, mken1205 approved these changes

2023-10-04 13:45 UTC, Charlesntwari approved these changes

2023-10-05 07:41 UTC, ceelogre requested changes
Your backend is not responding. 
<img width="1186" alt="image" src="https://github.com/atlp-rwanda/atlp-pulse-fn/assets/5022823/4bd534f7-4dc0-41a0-beb3-fbd0bfd7d0c2">

2023-10-05 08:54 UTC, ceelogre commented
Still  can't change the cover image.
<img width="1186" alt="image" src="https://github.com/atlp-rwanda/atlp-pulse-fn/assets/5022823/bc83aa6d-a628-40b6-a8d1-7d578aded1df">

2023-10-11 09:20 UTC, ceelogre approved these changes

2023-10-11 11:45 UTC, NTElissa approved these changes

2023-10-13 10:45 UTC, merged