fix-trainee-dashboard
atlp-rwanda/atlp-pulse-fn pull request #312
Opened 2023-10-04 13:19 UTC by Charlesntwari

# PR Description
this PR modify the designs dashboard of trainee so that it looks great than ever especially in dark mode

# Description of tasks that were expected to be completed
-double check and analyze  the logic used represent data in graphs
-modifying data representation designs in table format
-fixing all data on the screen properly

# How has this been tested?

-pull this PR
-run both server and frontend
-login as trainee and check on dashboard
(N.B: in case trainee doesn't have ratings for the sake of having better experience please first of all rate him/her as coordinator then back to check the changes)
# Number of Commits
1

# Screenshots (If appropriate)

# Please check this Checklist before you submit your PR:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

2023-10-04 13:49 UTC, nshutip approved these changes

2023-10-04 13:49 UTC, nshutip commented on src/components/ViewComment.tsx
Why was the color code changed on line 58 from #333131 to #8667F2 on line 62?

2023-10-04 14:14 UTC, Virgile1k approved these changes
checked and approved

2023-10-04 15:06 UTC, Charlesntwari commented on src/components/ViewComment.tsx
that color button was not matching with the code we follow, moreover it wasn't looking good enough in the dark mode.

2023-10-05 07:24 UTC, NTElissa approved these changes

2023-10-06 13:45 UTC, ceelogre requested changes
The phase element should retain the original color in light mode.
<img width="1186" alt="image" src="https://github.com/atlp-rwanda/atlp-pulse-fn/assets/5022823/0a92ba5f-0df7-4c71-b660-024ce25f7ac5">

2023-10-06 14:17 UTC, Charlesntwari commented
> The phase element should retain the original color in light mode. <img alt="image" width="1186" src="https://user-images.githubusercontent.com/5022823/273222934-0a92ba5f-0df7-4c71-b660-024ce25f7ac5.png">

Normally based on the logic of the system phase element comes with trainee ratings. that's why it does not appear on the dashboard of trainee with no performance ratings

2023-10-06 14:58 UTC, ceelogre commented
> > The phase element should retain the original color in light mode. <img alt="image" width="1186" src="https://user-images.githubusercontent.com/5022823/273222934-0a92ba5f-0df7-4c71-b660-024ce25f7ac5.png">
> 
> Normally based on the logic of the system phase element comes with trainee ratings. that's why it does not appear on the dashboard of trainee with no performance ratings

I'm talking about the whole div element not particularly the phase.

2023-10-11 19:01 UTC, ceelogre approved these changes

2023-10-11 19:02 UTC, merged