Fix fetch trainees on attendance
atlp-rwanda/atlp-pulse-fn pull request #313
Opened 2023-10-04 16:33 UTC by NdatimanaSamuel

# PR Description
this PR ,fix fetching of trainees on attendance list where if trainees is added by admin can be displayed even on coordinator attendance  

List all the tasks and sub-tasks that were assigned to you or that you assigned yourself. Make sure you check every completed task.

# How has this been tested?
-pull this PR
-run both server and frontend
-login as coordinator or admin  and add trainees will be appeared on dashboard of coordinator on attendance

# Number of Commits
1
# Screenshots (If appropriate)

# Please check this Checklist before you submit your PR:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

2023-10-12 14:29 UTC, Virgile1k approved these changes
Checked  and approved

2023-10-12 14:35 UTC, Charlesntwari approved these changes

2023-10-12 14:46 UTC, mken1205 approved these changes

2023-10-12 15:18 UTC, madebypatrick approved these changes

2023-10-13 09:29 UTC, ceelogre requested changes
When I try to rate attendance, it says week does not exist. Also remove log messages in the console.
![image](https://github.com/atlp-rwanda/atlp-pulse-fn/assets/5022823/781908c7-7e35-4105-8780-8db4da7cd393)

2023-10-20 13:03 UTC, Gentille-dev approved these changes

2023-10-23 09:28 UTC, Gentille-dev approved these changes

2024-09-26 09:56 UTC, ceelogre commented
Re-implemented.

2024-09-26 09:56 UTC, closed without merging