fix(bug):fix a super admin profile (#301)
atlp-rwanda/atlp-pulse-fn pull request #320
Opened 2023-10-11 09:04 UTC by KAYITARES

# PR Description

Please include a brief description of the pull request you want to raise.

# Description of tasks that were expected to be completed

List all the tasks and sub-tasks that were assigned to you or that you assigned yourself. Make sure you check evey completed task.

# How has this been tested?

Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

# Number of Commits

The number of commits should not exceed **2 commits**. In case they are more than that, please take your time and squash them.

# Screenshots (If appropriate)

# Please check this Checklist before you submit your PR:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

2023-10-13 07:54 UTC, Virgile1k approved these changes
Checked and approved

2023-10-13 07:55 UTC, NdatimanaSamuel approved these changes

2023-10-13 10:01 UTC, NTElissa approved these changes

2023-10-13 10:31 UTC, ceelogre approved these changes

2023-10-13 10:44 UTC, Gentille-dev approved these changes

2023-10-16 15:04 UTC, ceelogre requested changes
Work on the console warnings. Also remove the log messages.
![image](https://github.com/atlp-rwanda/atlp-pulse-fn/assets/5022823/ef140686-489a-4aa6-8885-ff70a30f7db0)

2023-10-19 21:32 UTC, ceelogre commented
This appears at first login: 
<img width="1433" alt="image" src="https://github.com/atlp-rwanda/atlp-pulse-fn/assets/5022823/cefb1bac-2c72-4bfa-89d7-f23d17833091">
This appears when you go to profile:
![Uploading image.png…]()

2023-11-06 07:37 UTC, ceelogre approved these changes

2023-11-06 07:38 UTC, merged