Coordinator should update ratings
atlp-rwanda/atlp-pulse-fn pull request #343
Opened 2023-11-09 18:56 UTC by Dyves1

# PR Description

Please include a brief description of the pull request you want to raise.

# Description of tasks that were expected to be completed

List all the tasks and sub-tasks that were assigned to you or that you assigned yourself. Make sure you check evey completed task.

# How has this been tested?

Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

# Number of Commits

The number of commits should not exceed **2 commits**. In case they are more than that, please take your time and squash them.

# Screenshots (If appropriate)

# Please check this Checklist before you submit your PR:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

2023-11-22 14:59 UTC, irakozejules approved these changes

2023-11-22 15:04 UTC, bryan936M approved these changes

2023-11-24 08:50 UTC, ceelogre requested changes
As per my messages on slack, the edit button appears in scenarios where it shouldn't.

There should be a cancel button in case someone wants to cancel editing ratings.
<img width="698" alt="image" src="https://github.com/atlp-rwanda/atlp-pulse-fn/assets/5022823/a44cb489-ebcb-4be5-9cda-873b66510598">

2023-11-24 14:04 UTC, ceelogre approved these changes

2023-11-24 14:04 UTC, ceelogre commented on src/components/ratings/ViewWeeklyRatings.tsx
> +  const [updateRatings, { loading: updateRatingLoading, data, error }] =
Unused-vars.

2023-11-24 14:06 UTC, merged