fix ticket design and responsiveness on dashboard
atlp-rwanda/atlp-pulse-fn pull request #344
Opened 2023-11-12 21:04 UTC by NdatimanaSamuel

# PR Description
ticket design when you click on read more button was not responsiveness and was not some space between buttons, and some color was not perfect
Please include a brief description of the pull request you want to raise.
# Description of tasks that were expected to be completed
- show ticket responsiveness
- change color where is needed
- add space and arrange items in good condition which is attractive

List all the tasks and sub-tasks that were assigned to you or that you assigned yourself. Make sure you check every completed task.

# How has this been tested?

- login as trainee/coordinator access ticket  menu then check it responsiveness
- login as admin/super-admin access ticket  menu then check it responsiveness

Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

# Number of Commits

The number of commits should not exceed **2 commits**. In case they are more than that, please take your time and squash them.

# Screenshots (If appropriate)
![pikone](https://github.com/atlp-rwanda/atlp-pulse-fn/assets/77956577/8cd9d02a-1829-4a37-a0c2-0cd16de137fe)
![piktwo](https://github.com/atlp-rwanda/atlp-pulse-fn/assets/77956577/041a252f-2de7-4e80-b2d1-c952f54db0d3)

# Please check this Checklist before you submit your PR:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

2023-11-13 07:20 UTC, KAYITARES approved these changes

2023-11-13 12:33 UTC, NTElissa approved these changes

2023-11-13 13:36 UTC, madebypatrick approved these changes

2023-11-16 21:59 UTC, Dyves1 approved these changes

2023-11-17 04:12 UTC, Gabriel-mdv approved these changes
it is all working well

2023-11-17 08:37 UTC, ceelogre requested changes
The max width is still tool small for content, there is so much space around the items.
![image](https://github.com/atlp-rwanda/atlp-pulse-fn/assets/5022823/a249e32d-c962-48c3-9680-e5b98f16332a)

2023-11-17 08:37 UTC, ceelogre commented on src/pages/AllTickets.tsx
> +              <div className="flex flex-col md:flex-row items-center justify-center md:justify-between px-6 pt-0 pb-6">
This may have to be fixed.

2023-11-17 11:29 UTC, ceelogre approved these changes

2023-11-17 11:29 UTC, merged