Ft notification
atlp-rwanda/atlp-pulse-fn pull request #40
Opened 2022-07-22 09:26 UTC by PatrickTUy

# PR Description
Creation of notifications
# Description of tasks that were expected to be completed

1.  users are able to see notifications
2. users are able to mark notification as read 
3. users are able to delete notification
4. responsiveness

# How has this been tested?
We created test that implemented the functionality of all mouse clicks and key downs to run all  the functions of reading and deleting.
in the terminal, type npm run test && npm run coverage
# Number of Commits
8 commits

# Screenshots (If appropriate)
<img width="1431" alt="Screen Shot 2022-07-22 at 10 56 57" src="https://user-images.githubusercontent.com/95919588/180403932-98266c39-e003-41ec-af82-822db308e119.png">
<img width="1436" alt="Screen Shot 2022-07-22 at 10 54 39" src="https://user-images.githubusercontent.com/95919588/180404050-4effbede-d3d9-40a8-b390-8924ea8b6f78.png">

# Please check this Checklist before you submit your PR:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

2022-07-22 09:28 UTC, feyton commented
I deployed a review app for you to try out this pull request 👇🏽

Heroku App: https://devpulse-review-app-40.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

2022-07-25 16:11 UTC, chanceDira approved these changes
This looks good 👍

2022-07-25 17:14 UTC, feyton commented on package.json
> +    "test": "npx jest -u",
This command should not change as the purpose of the tests is to check if other files were affected. If you just run the command with `-u`, then it serves no purpose.

2022-07-25 17:25 UTC, feyton requested changes
### Critical changes

Please refer to the comments I left especially in the package.json file

2022-07-25 17:25 UTC, feyton commented on package.json
> +    "coverage": "jest --coverage --silent -u",
### Critical 

Same here, restore the previous command. You have to be sure to update snapshot before you push the code not when running the github actions

2022-07-25 17:25 UTC, feyton commented on src/components/Notification.tsx
> +const notificationDummy = [
Can we move those data outside the function into its own file

2022-07-25 17:25 UTC, feyton commented on src/components/Notification.tsx
> +                    data-testid={index === 0 && 'read'}
don't use a variable data-test-id as they will break your code. You can safely mock the data you are expecting same case with an `api` call

2022-07-25 17:25 UTC, feyton commented on src/components/Notification.tsx
> +                      className="border-[rgba(95,91,91,0.5)] dark:fill-white h-[20px] w-[20px] cursor-pointer"
Avoid absolute values in the styling, instead, put the color in our `tailwind.css.config` to make it easier to replace the colors when the time comes

2022-07-26 07:16 UTC, Dev-nkundineza approved these changes
Great job @PatrickTUy and @Tsa2341

2022-07-27 06:45 UTC, jeandamascyifuzo approved these changes
Geat Job

2022-07-27 08:02 UTC, samyshyaka requested changes
- I think it's better if the background is not blurred when the drop-down appears
- Also, you can try to move the drop-down closer to the header. I think it will be even better if it touches the header
- Lastly, try to shift the drop-down a few pixels to the right to make sure that it is right under the notification icon

2022-07-27 14:32 UTC, PatrickTUy commented
> * I think it's better if the background is not blurred when the drop-down appears
> * Also, you can try to move the drop-down closer to the header. I think it will be even better if it touches the header
> * Lastly, try to shift the drop-down a few pixels to the right to make sure that it is right under the notification icon

We had actually implemented what was in figma  which was approved [ link ](https://www.figma.com/proto/Q4kozKNucJX4kJsHgnB4Vi/ATLP-UI-V2?node-id=1699%3A24308&scaling=contain&page-id=58%3A97&starting-point-node-id=216%3A1284)

2022-07-27 18:04 UTC, feyton approved these changes

2022-07-27 19:09 UTC, ceelogre reviewed
There are no instructions on how to test this.

2022-07-28 08:49 UTC, ceelogre submitted a review, later dismissed
1. Let's use black people for profile images
2. On mobile devices, the notification container occupies the whole screen

![IMG_D2BB256E07D7-1](https://user-images.githubusercontent.com/5022823/181463048-55e02c7e-efc5-48f6-8f64-7a104faf9607.jpeg)
.

2022-07-29 10:58 UTC, ceelogre approved these changes

2022-07-29 11:06 UTC, merged