Skeleton loader match to respective layout
atlp-rwanda/atlp-pulse-fn pull request #437
Opened 2024-08-29 13:01 UTC by Dawaic6

# PR Description

This PR reconstructs the skeleton loaders across the entire application to better match the respective page layouts. The goal is to enhance the user experience by providing more accurate visual placeholders that align with the design and content of each page while the data is loading.

# Description of tasks that were expected to be completed

-  Reconstructed skeleton loaders for the **Dashboard page** to match the card and graph components layout.
-  Redesigned skeleton loaders for the **Organizations page** to reflect the table and filter input layout.
-  Updated skeleton loaders on the **Tickets page** to align with the ticket list and detailed view sections.
-  Refined skeleton loaders for the **Admins page** to match the admin list and control components.
-  Implemented loaders for the **Domains page** to mirror the grid and form layout for domain management.
-  Created loaders that fit the **Calendar page's** calendar and event list layout.
-  Updated skeleton loaders for the **Help page** to align with the FAQ and help sections.
-  Ensured consistency in loader colors, sizes, and spacing across all pages.
-  Made all skeleton loaders responsive to adapt well to different screen sizes.

# How has this been tested?

**Manual Testing:** Verified each page's skeleton loaders to ensure they align with the respective page layout and design on various devices (desktop, tablet, mobile).

- Navigated through each page to check that loaders appear correctly while data is being fetched.
- Checked that the loaders are responsive and adapt well to different screen sizes.
- Ensured no existing functionality was broken by the new loaders.

# Screenshots (If appropriate)

# Please check this Checklist before you submit your PR:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

2024-09-04 10:32 UTC, andremugabo approved these changes
LGTM

2024-09-04 15:15 UTC, janet-barbie approved these changes

2024-09-05 08:14 UTC, shema-surge approved these changes
Can u put some space between the "add Event" button and the skeleton on the calendar page

2024-09-05 12:57 UTC, JacquelineTuyisenge approved these changes

2024-09-05 15:08 UTC, ncutixavier requested changes
In general, Unnecessary changes/formats are not allowed

2024-09-05 15:08 UTC, ncutixavier commented on src/Skeletons/calSkeleton.tsx
We need to have meaningful files (table.skeleton.tsx)

2024-09-05 15:08 UTC, ncutixavier commented on src/components/Calendar.tsx
> +        console.log({ eventsError: error });
Remove all unnecessary logs

2024-09-05 15:08 UTC, ncutixavier commented on src/components/Calendar.tsx
> +  );
Avoid unnecessary changes anywhere

2024-09-06 17:16 UTC, ncutixavier approved these changes

2024-09-06 17:39 UTC, Bananayosostene approved these changes

2024-09-09 09:42 UTC, Salim-54 reviewed
Resolve the conflicts

2024-09-09 12:25 UTC, merged