Fetch invitation statistics (#463)
atlp-rwanda/atlp-pulse-fn pull request #498
Opened 2024-09-17 12:46 UTC by elijahladdie

# PR Description

Please include a brief description of the pull request you want to raise.

# Description of tasks that were expected to be completed

List all the tasks and sub-tasks that were assigned to you or that you assigned yourself. Make sure you check evey completed task.

# How has this been tested?

Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

# Number of Commits

The number of commits should not exceed **2 commits**. In case they are more than that, please take your time and squash them.

# Screenshots (If appropriate)

# Please check this Checklist before you submit your PR:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

2024-09-17 12:58 UTC, kanu-cast approved these changes

2024-09-17 13:17 UTC, pacifiquemboni approved these changes

2024-09-17 20:37 UTC, aimedivin requested changes
@elijahladdie, @Christian-Ishimwe 
How can admin delete his/her self pls fix that . Ensure that a warning modal is displayed before deletion, asking for confirmation if admin really wants to proceed with deleting the account, also make sure that any deleted user is immediately signed out where they are currently logged in 

![image](https://github.com/user-attachments/assets/134b162b-9583-4b8c-96a7-f8cb29b7eec2)

2024-09-18 09:30 UTC, elijahladdie commented
> How can admin delete his/her self pls fix that . Ensure that a warning modal is displayed before deletion, asking for confirmation if admin really wants to proceed with deleting the account, also make sure that any deleted user is immediately signed out where they are currently logged in

> resolved @aimedivin

2024-09-19 11:45 UTC, Christian-Ishimwe approved these changes

2024-09-20 13:32 UTC, aimedivin approved these changes

2024-09-22 11:37 UTC, amiparadis250 approved these changes

2024-10-03 09:35 UTC, closed without merging