Chore: add redirect handler
atlp-rwanda/atlp-pulse-fn pull request #508
Opened 2024-09-24 13:33 UTC by fredshema

### PR Description

This PR adds a page that will handle redirections from external links to other resources of pulse like the mobile app.

### Description of tasks that were expected to be completed

- [x] Handle redirect and define required query parameters.

### How has this been tested?

Run the app and try opening the app on this link: [http://localhost:3001/redirect?path=/register/123](http://localhost:3001/redirect?path=/register/123). There should be a redirect to the specified path.

### Screenshots (If appropriate)
N/A

2024-09-25 10:23 UTC, pacifiquemboni approved these changes

2024-09-25 21:39 UTC, MugemaneBertin2001 approved these changes

2024-09-25 22:37 UTC, MugemaneBertin2001 requested changes
Check on this @fredshema 
![Screenshot 2024-09-26 003544](https://github.com/user-attachments/assets/797ce962-4e50-4ebb-8694-9eeced53b8f4)

2024-09-25 23:11 UTC, fredshema commented
This happens when a user doesn't have the mobile app installed. It will redirect to a fallback url specified in the link or the homepage. Did it redirect for you?

2024-09-26 08:35 UTC, MugemaneBertin2001 approved these changes

2024-09-26 08:46 UTC, ncutixavier approved these changes

2024-09-26 08:46 UTC, merged