#502 web-perfomance load time
atlp-rwanda/atlp-pulse-fn pull request #511
Opened 2024-09-24 17:15 UTC by JacquelineTuyisenge

# PR Description

This pull request focuses on optimizing the application's build performance by removing Webpack and replacing it with Vite as the build tool.

# Description of tasks that were expected to be completed

- [x] Removed Webpack from the project due to its slower bundling performance compared to Vite.
- [x] Integrated Vite for faster development and build times.
- [x] Updated project configurations to support Vite as the new bundler.

# How has this been tested?

I have tested the application by:

1. Building the application using `npm run build` with Vite.
2. Serving the application locally using `npm run dev`.
3. Measuring the initial load time using performance monitoring tools (e.g., Chrome DevTools, stop watch).
4. Verifying that the application functions correctly without any errors after the migration.

The initial load times have improved significantly due to Vite's optimized bundling process.

# Number of Commits

**1 commit**.

# Screenshots (If appropriate)

N/A

# Please check this Checklist before you submit your PR:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generates no warnings
- [ ] My test coverage meets the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

2024-09-25 10:13 UTC, Bananayosostene approved these changes

2024-09-26 17:23 UTC, Tuyisenge2 approved these changes

2024-09-30 14:21 UTC, ceelogre requested changes
In this file: 
https://github.com/atlp-rwanda/atlp-pulse-fn/blob/fix-load-time-502/.github/workflows/do.yml

Change `on push` to on `pull_request` so we can test the performance on beta.

2024-10-01 11:11 UTC, Bananayosostene approved these changes

2024-10-02 13:20 UTC, ceelogre commented
Revert the change (on pull_request) https://github.com/atlp-rwanda/atlp-pulse-fn/pull/511#pullrequestreview-2337724525 then we will merge.

2024-10-02 22:11 UTC, ceelogre approved these changes

2024-10-02 22:12 UTC, merged