Fix:redirect handler
atlp-rwanda/atlp-pulse-fn pull request #517
Opened 2024-09-26 14:59 UTC by fredshema

### PR Description

Fixes issues with redirecting on browsers that needs user input and make sure fallbacks are loaded correctly

### Description of tasks that were expected to be completed

Add a redirection link for users to click on.

### How has this been tested?

Use the path `/redirect` as previously shown in #508

2024-09-27 11:51 UTC, ncutixavier approved these changes

2024-09-27 12:55 UTC, Mbabazi12 approved these changes

2024-09-30 11:28 UTC, MugemaneBertin2001 requested changes
It still requires the org to log in, which is unnecessary for the user to register.

2024-10-03 14:14 UTC, pacifiquemboni approved these changes

2024-10-03 18:29 UTC, MugemaneBertin2001 approved these changes
The requested changes are corrected now we can go on with this pr

![Screenshot 2024-10-03 202829](https://github.com/user-attachments/assets/4d9cc72c-1e2d-45e7-8f33-c83973afcf32)

2024-10-03 23:47 UTC, merged