Fix: Update Trainee Dashboard
atlp-rwanda/atlp-pulse-fn pull request #528
Opened 2024-10-02 09:22 UTC by kanu-cast

# PR Description

Please include a brief description of the pull request you want to raise.

# Description of tasks that were expected to be completed

List all the tasks and sub-tasks that were assigned to you or that you assigned yourself. Make sure you check evey completed task.

# How has this been tested?

Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

# Number of Commits

The number of commits should not exceed **2 commits**. In case they are more than that, please take your time and squash them.

# Screenshots (If appropriate)

# Please check this Checklist before you submit your PR:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

2024-10-04 09:50 UTC, rwemakevin approved these changes

2024-10-04 10:08 UTC, elijahladdie approved these changes

2024-10-04 10:57 UTC, aimedivin approved these changes

2024-10-04 11:07 UTC, amiparadis250 approved these changes

2024-10-31 21:29 UTC, aimedivin reviewed
@kanu-cast , fix the text color for this combobox while them for page is in dark mode

![image](https://github.com/user-attachments/assets/9d80d387-47d1-47ad-ba52-d995d28619c7)

2024-10-31 21:29 UTC, aimedivin commented on src/pages/TraineeDashboard.tsx
> +    console.log('thiis is raw',data)
@kanu-cast remove this console.log()

2024-10-31 21:32 UTC, aimedivin requested changes
@kanu-cast , fix the text color for this combobox while them for page is in dark mode

![Screenshot from 2024-10-31 23-28-23](https://github.com/user-attachments/assets/7eaba071-bd15-4892-8cfe-98887e06f3c1)

2024-10-31 21:32 UTC, aimedivin commented on src/pages/TraineeDashboard.tsx
> +    console.log('thiis is raw',data)
@kanu-cast remove this console.log()

2024-11-04 06:15 UTC, aimedivin requested changes

2024-11-04 06:15 UTC, aimedivin commented on src/pages/TraineeDashboard.tsx
> +                    <select
@kanu-cast for the above-requested change, apply background-color property for this element it will fix it.

2024-11-04 06:15 UTC, aimedivin commented on src/pages/TraineeDashboard.tsx
> +                            <select
@kanu-cast same here, apply different background-color property for this element on both dark and light mode it will fix it.

2024-11-14 21:14 UTC, aimedivin approved these changes

2024-11-15 07:43 UTC, aimedivin requested changes
@kanu-cast , the filters for page content aren't functioning correctly, performance score isn’t updating based on the selected time range, and the data displayed in the performance sprint table doesn’t match the chosen time, kindly fix that as soon as possible .

2024-11-19 11:51 UTC, igorihimbazwe approved these changes

2024-11-19 12:08 UTC, elijahladdie approved these changes

2024-11-20 06:24 UTC, aimedivin approved these changes

2024-11-20 15:29 UTC, merged