adding undrop trainee feature
atlp-rwanda/atlp-pulse-fn pull request #532
Opened 2024-10-02 14:02 UTC by elijahladdie

# PR Description

Please include a brief description of the pull request you want to raise.

# Description of tasks that were expected to be completed

List all the tasks and sub-tasks that were assigned to you or that you assigned yourself. Make sure you check evey completed task.

# How has this been tested?

Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

# Number of Commits

The number of commits should not exceed **2 commits**. In case they are more than that, please take your time and squash them.

# Screenshots (If appropriate)

# Please check this Checklist before you submit your PR:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

2024-10-02 16:16 UTC, igorihimbazwe approved these changes

2024-10-03 14:27 UTC, aimedivin requested changes
@elijahladdie , Could you please provide description for this PR

2024-10-04 07:31 UTC, amiparadis250 approved these changes

2024-10-04 08:39 UTC, aimedivin approved these changes

2024-10-04 10:07 UTC, merged