#582 Re-designing seach bar, filter and sorting
atlp-rwanda/atlp-pulse-fn pull request #586
Opened 2024-10-15 14:39 UTC by niyobertin

-Ensure that the serch bar ,filter and sort are re-disigend well -ensire that  the invite button remove from trainee page

# PR Description

Please include a brief description of the pull request you want to raise.

# Description of tasks that were expected to be completed

List all the tasks and sub-tasks that were assigned to you or that you assigned yourself. Make sure you check evey completed task.

# How has this been tested?

Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

# Number of Commits

The number of commits should not exceed **2 commits**. In case they are more than that, please take your time and squash them.

# Screenshots (If appropriate)

# Please check this Checklist before you submit your PR:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

2024-10-16 09:07 UTC, UwicyezaG approved these changes

2024-10-16 10:24 UTC, Ndevu12 requested changes
cool

2024-10-16 10:25 UTC, Ndevu12 approved these changes

2024-10-16 10:31 UTC, jniyonkuru approved these changes

2024-10-16 10:45 UTC, mpanoathos approved these changes

2024-10-17 10:50 UTC, ncutixavier approved these changes

2024-10-17 10:54 UTC, merged