fixing new tickets button color and trimming message
atlp-rwanda/atlp-pulse-fn pull request #589
Opened 2024-10-17 05:09 UTC by amiparadis250

# PR Description

Fixing all icolor inconsistency and trimming message on tickets  

# Description of tasks that were expected to be completed

.New tickets button color changed to purple instead of  blue

# How has this been tested?

 simply you can go to this link https://metron-devpulse-git-fix-tickets-crud-metron.vercel.app/ then you login as TTl , Coordinator or Admin , then you can start manipulating

# Number of Commits
 1

# Screenshots (If appropriate)
![Screenshot 2024-10-17 070707](https://github.com/user-attachments/assets/17c34e0d-b50f-4723-9a34-a58129e7c010)

# Please check this Checklist before you submit your PR:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

2024-10-17 11:10 UTC, kanu-cast approved these changes

2024-10-17 11:58 UTC, Calebgisa72 approved these changes

2024-10-18 06:04 UTC, aimedivin requested changes, later dismissed
@amiparadis250, also work on that submit button, and the message content
![image](https://github.com/user-attachments/assets/822321dd-5656-4272-8e6a-ef3f0c215226)

![image](https://github.com/user-attachments/assets/4c1077c1-b3fb-4cbd-b4eb-c06ee53860f4)

2024-10-21 08:09 UTC, igorihimbazwe approved these changes

2024-11-19 10:15 UTC, ceelogre approved these changes

2024-11-19 10:17 UTC, merged