#225 fx-Remove ratings legacy feature
atlp-rwanda/atlp-pulse-fn pull request #594
Opened 2024-10-18 12:14 UTC by Bananayosostene

## PR Description
This PR addresses the removal of legacy features on the frontend, specifically the non-implemented fields qualityRemark, quantityRemark, and professionalismRemark, which were redundant and not utilized. The feedback and rating functionality remain as the primary feature for user feedback.

## Description of tasks that were expected to be completed
Confirmed that the legacy fields were not implemented on the frontend.
Verified that no changes or updates were required in terms of visual or functional implementation related to these fields.
Cleaned up any mentions or potential references to the fields if found.
How has this been tested?
Manual review: Ensured that no unintended front-end changes related to qualityRemark, quantityRemark, and professionalismRemark exist.
Browser testing: Verified that the existing feedback and ratings features work as expected without any issues.
Number of Commits
1 commit for the changes. Squashed if necessary.

## Screenshots (If appropriate)
(Optional)

Please check this Checklist before you submit your PR:
 My code follows the style guidelines of this project.
 I have performed a self-review of my code.
 My code generates no warnings.
 My test coverage meets the set test coverage threshold.
 There are no vulnerabilities.
 There are no conflicts with the base branch.

2024-10-21 06:58 UTC, Tuyisenge2 approved these changes

2024-10-21 14:35 UTC, Dawaic6 approved these changes

2024-10-21 22:23 UTC, shema-surge requested changes
1. Remove bodyQuality, bodyQuantity and bodyProfessional
2. "generalRemarks" is no longer needed, keep "feedbacks" only

2024-10-22 15:04 UTC, JacquelineTuyisenge approved these changes

2024-10-22 15:05 UTC, shema-surge approved these changes

2024-10-29 14:42 UTC, merged