Feat: Logout dropdown
atlp-rwanda/atlp-pulse-fn pull request #61
Opened 2022-08-19 09:08 UTC by rukundo-kevin

# PR Description
Profile Page
# Description of tasks that were expected to be completed

1.  users are able view a dropdown when they click their profile pic or avatar.

# functionality 

- Sign in with an email e.g(admin@random.com) through this [link]( https://devpulse-review-app-50.herokuapp.com/), use any characters of your choice as password 
- Click the profile avar on top-right corner.

# Screenshots (If appropriate)
<img width="1440" alt="Screen Shot 2022-08-19 at 11 07 10" src="https://user-images.githubusercontent.com/38954786/185585476-4b9dc4da-93d1-492a-a081-61e0cd03ef8d.png">
<img width="324" alt="Screen Shot 2022-08-19 at 11 07 32" src="https://user-images.githubusercontent.com/38954786/185585550-499a2c7a-55c9-4315-8e36-679be2a96b77.png">
<img width="782" alt="Screen Shot 2022-08-19 at 11 07 53" src="https://user-images.githubusercontent.com/38954786/185585633-ba8c948c-0fe8-4a82-b0a7-9207ec792fcb.png">

# Please check this Checklist before you submit your PR:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My code generate no warnings
- [x] My test coverage meet the set test coverage threshold
- [x] There are no vulnerabilities
- [x] There are no conflicts with the base branch

2022-08-19 09:10 UTC, feyton commented
I deployed a review app for you to try out this pull request 👇🏽

Heroku App: https://devpulse-review-app-61.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

2022-08-22 09:28 UTC, chanceDira approved these changes
Nice job.

2022-08-22 14:44 UTC, IIshimwe commented
Doesn't it look better if you remove color changes on the text and replace it with color changes on the background for better visibility of what hovered on?

2022-08-22 15:58 UTC, feyton requested changes
### Request changes
@rukundo-kevin 
Please look into the comments I left for some minor fixes.
Kudos for the great feature that was really needed

2022-08-22 15:58 UTC, feyton commented on src/components/ProfileDropdown.tsx
> +                    <Link to="#link">{t('Preference')}</Link>
You can change the link to point to the `settings` page

2022-08-22 15:58 UTC, feyton commented on src/components/ProfileDropdown.tsx
> +                  <p className="font-semibold text-gray-600 dark:text-white p-1 hover:bg-gray-600 hover:text-gray-200 dark:hover:bg-gray-300 dark:hover:text-gray-900">
Give the `menu` the full width to fix this issue of hover effects different for the `signout` to the others

![image](https://user-images.githubusercontent.com/28519395/185965514-aa70ec45-0599-49d1-900a-5bf3d9dbcfdf.png)

2022-08-23 06:31 UTC, feyton approved these changes

2022-08-23 07:28 UTC, IIshimwe approved these changes
This is nice @rukundo-kevin

2022-08-23 12:30 UTC, ceelogre approved these changes

2022-08-23 12:30 UTC, merged