#482Ft-Mix use of translation
atlp-rwanda/atlp-pulse-fn pull request #612
Opened 2024-10-29 11:01 UTC by Ke-bean

# PR Description

There's a title in french that's with an english paragraph.

# Description of tasks that were expected to be completed

List all the tasks and sub-tasks that were assigned to you or that you assigned yourself. Make sure you check evey completed task.

# How has this been tested?

Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

# Number of Commits

The number of commits should not exceed **2 commits**. In case they are more than that, please take your time and squash them.

# Screenshots (If appropriate)

# Please check this Checklist before you submit your PR:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

2024-10-29 11:39 UTC, kanu-cast approved these changes

2024-10-30 13:15 UTC, aimedivin requested changes

2024-10-30 13:15 UTC, aimedivin commented on public/locales/kn/translation.json
> +  "goal": "Performance management/analysis",
@Ke-bean the translation of this sentence to kinyarwanda is wrong work on it

2024-11-07 14:37 UTC, Calebgisa72 approved these changes

2024-11-07 16:40 UTC, igorihimbazwe approved these changes

2024-11-07 16:44 UTC, aimedivin approved these changes

2024-11-11 22:30 UTC, elijahladdie approved these changes

2024-11-12 19:10 UTC, Salim-54 commented
The branch preview should have a valid backend connection URL.

2024-11-15 10:25 UTC, Ke-bean commented
> The branch preview should have a valid backend connection URL.
The changes I made was on the homepage and they didn't include any backend changes. It was only some typography and texting that I was fixing here @Salim-54

2024-11-21 14:36 UTC, merged