adding community page
atlp-rwanda/atlp-pulse-fn pull request #624
Opened 2024-11-11 23:08 UTC by elijahladdie

# PR Description

Please include a brief description of the pull request you want to raise.

# Description of tasks that were expected to be completed

List all the tasks and sub-tasks that were assigned to you or that you assigned yourself. Make sure you check evey completed task.

# How has this been tested?

Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

# Number of Commits

The number of commits should not exceed **2 commits**. In case they are more than that, please take your time and squash them.

# Screenshots (If appropriate)

# Please check this Checklist before you submit your PR:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

2024-11-15 04:38 UTC, aimedivin requested changes
@elijahladdie @hatfelicien , when I reply to asked question, it's thread disappear, kindly look into it.

2024-11-15 09:18 UTC, igorihimbazwe approved these changes

2024-11-15 09:20 UTC, hatfelicien approved these changes

2024-11-15 09:29 UTC, aimedivin approved these changes

2024-11-15 11:36 UTC, Salim-54 commented
Miss valid backend connection URL

2024-11-15 12:39 UTC, merged

2024-11-16 10:16 UTC, RWEMAREMY reviewed
Great work