fixing community page theme
atlp-rwanda/atlp-pulse-fn pull request #628
Opened 2024-11-17 14:02 UTC by elijahladdie

# PR Description

Please include a brief description of the pull request you want to raise.

# Description of tasks that were expected to be completed

List all the tasks and sub-tasks that were assigned to you or that you assigned yourself. Make sure you check evey completed task.

# How has this been tested?

Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

# Number of Commits

The number of commits should not exceed **2 commits**. In case they are more than that, please take your time and squash them.

# Screenshots (If appropriate)

# Please check this Checklist before you submit your PR:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

2024-11-18 15:57 UTC, kanu-cast approved these changes

2024-11-18 16:42 UTC, igorihimbazwe approved these changes

2024-11-18 18:00 UTC, hatfelicien approved these changes

2024-11-19 05:52 UTC, aimedivin requested changes

2024-11-19 05:52 UTC, aimedivin commented on src/ProtectedRoute.tsx
> -import { useSearchParams } from 'react-router-dom';
@elijahladdie Could you readd this  import statement? It’s still being used in the file

2024-11-19 08:10 UTC, elijahladdie commented on src/ProtectedRoute.tsx
> -import { useSearchParams } from 'react-router-dom';
@aimedivin it is still there look closely

2024-11-19 10:51 UTC, aimedivin approved these changes

2024-11-19 12:13 UTC, merged