Fx sidebar scroll
atlp-rwanda/atlp-pulse-fn pull request #632
Opened 2024-11-19 07:34 UTC by igorihimbazwe

# PR Description

This Pr fixes the sidebar scroll issue

# Description of tasks that were expected to be completed

Made sidebar fixed whaen main content is being scrolled and sidebar can be scrolled independently

# How has this been tested?
`  git clone https://github.com/atlp-rwanda/atlp-pulse-fn.git
  cd atlp-pulse-fn
  git checkout fix-siderbar-scroll
  npm i
  npm run dev
  or
  npm run test`

# Number of Commits

1

# Please check this Checklist before you submit your PR:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My code generate no warnings
- [x] My test coverage meet the set test coverage threshold
- [x] There are no vulnerabilities
- [x] There are no conflicts with the base branch

2024-11-19 08:19 UTC, Calebgisa72 approved these changes

2024-11-19 08:24 UTC, hatfelicien approved these changes

2024-11-19 10:42 UTC, aimedivin approved these changes

2024-11-20 10:08 UTC, aimedivin requested changes
@igorihimbazwe make sure contents are aligned well

![image](https://github.com/user-attachments/assets/0b0b20a2-f0cf-4f6e-bcca-9959d106a4ce)

2024-11-20 11:44 UTC, aimedivin approved these changes

2024-11-20 15:29 UTC, merged