Fix: Dynamic titles
atlp-rwanda/atlp-pulse-fn pull request #64
Opened 2022-08-24 05:13 UTC by rukundo-kevin

# PR Description
Dynamic title
# Description of tasks that were expected to be completed
    - Change title according to the current page
    - translation
# Please check this Checklist before you submit your PR:
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ x] There are no vulnerabilities
- [ x] There are no conflicts with the base branch

2022-08-24 08:29 UTC, feyton commented
I deployed a review app for you to try out this pull request 👇🏽

Heroku App: https://devpulse-review-app-64.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

2022-08-24 10:58 UTC, feyton approved these changes
@rukundo-kevin 
This is great work, the only issue is related to the re-arrangement of the title and the format to match

```
Welcome |Devpulse
```
That would look better, in terms of core functionality, this is approved

2022-08-25 08:33 UTC, IIshimwe approved these changes

2022-08-25 16:03 UTC, Procech20 approved these changes

2022-08-26 08:09 UTC, ceelogre requested changes
Certain titles are not translated.
<img width="812" alt="image" src="https://user-images.githubusercontent.com/5022823/186854461-ef902153-5d6b-4f50-bec6-3952f7b42553.png">
<img width="812" alt="image" src="https://user-images.githubusercontent.com/5022823/186854517-2306b7d1-96b8-4385-b4fe-96575e05effc.png">

2022-08-29 09:03 UTC, chanceDira approved these changes

2022-08-29 09:32 UTC, ceelogre approved these changes

2022-08-29 09:32 UTC, merged