ft: add pagination
atlp-rwanda/atlp-pulse-fn pull request #75
Opened 2022-08-30 07:15 UTC by jeandamascyifuzo

# PR Description
Please include a brief description of the pull request you want to raise.
# Description of tasks that were expected to be completed
List all the tasks and sub-tasks that were assigned to you or that you assigned yourself. Make sure you check evey completed task.
# How has this been tested?
Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
# Number of Commits
The number of commits should not exceed **2 commits**. In case they are more than that, please take your time and squash them.
# Screenshots (If appropriate)
# Please check this Checklist before you submit your PR:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

2022-08-30 07:17 UTC, feyton commented
I deployed a review app for you to try out this pull request 👇🏽

Heroku App: https://devpulse-review-app-75.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

2022-08-31 07:18 UTC, rukundo-kevin requested changes
The trainee  and ratings tables still don't have pagination 
<img width="1440" alt="Screen Shot 2022-08-31 at 09 17 56" src="https://user-images.githubusercontent.com/38954786/187617021-bcd021de-0ccb-495f-b7a9-7a0753c9519b.png">

2022-09-01 08:06 UTC, chanceDira approved these changes
Good work @jeandamascyifuzo. You can increase your test coverage to make this ready.

2022-09-01 09:09 UTC, Procech20 approved these changes

2022-09-01 09:28 UTC, rukundo-kevin requested changes
Great work @jeandamascyifuzo , but still a few tables to add pagination to.
Some tables when you are logged in as Trainee  don't have paginations
 - Performance table
 - Sessions table
And when you are logged in as a coordinator the Ratings table don't have pagination

<img width="1440" alt="Screen Shot 2022-09-01 at 11 22 30" src="https://user-images.githubusercontent.com/38954786/187879933-1869e373-3c65-4b64-b31a-e22163d9ff68.png">

2022-09-01 11:23 UTC, feyton requested changes
@jeandamascyifuzo 

Please check the comments I left

2022-09-01 11:23 UTC, feyton commented on src/containers/Routes.tsx
> +          {/* <Route path="/test" element={<Test />} /> */}
Remove this line

2022-09-01 11:23 UTC, feyton commented on src/containers/admin-dashBoard/ManagerRoles.tsx
> +                          if (
Please re-check the way you rebased. You have affected previous features of @chanceDira

2022-09-01 11:23 UTC, feyton commented on src/pages/AdminTraineeDashboard.tsx
> +                                      ? 'bg-light-bg dark:bg-dark-tertiary'
Same rebase issue happened here

2022-09-01 11:23 UTC, feyton commented on src/pages/AdminTraineeDashboard.tsx
> +                                      ? 'bg-light-bg dark:bg-dark-tertiary'
From line 232 to 247 should no be there

2022-09-01 15:51 UTC, rukundo-kevin approved these changes

2022-09-02 07:45 UTC, ceelogre requested changes
Filtering is affected by pagination. Take a look at the video.
https://user-images.githubusercontent.com/5022823/188084347-4aebea19-52c8-4c27-9dbc-49b104e2dab3.mov

2022-09-02 08:24 UTC, jeandamascyifuzo commented
> 

@ceelogre 
Right now, I am not aware of how I can implement it, might take some time

2022-09-02 08:32 UTC, feyton approved these changes

2022-09-07 10:58 UTC, Dev-nkundineza requested changes
<img width="473" alt="Screen Shot 2022-09-07 at 12 56 57" src="https://user-images.githubusercontent.com/79087014/188862005-cacf9380-3a90-424e-980c-a1890aa50c44.png">

Great work @jeandamascyifuzo , can we improve UX in the light theme.

2022-09-07 12:19 UTC, chanceDira approved these changes

2022-09-07 12:43 UTC, Dev-nkundineza submitted a review, later dismissed
<img width="1165" alt="Screen Shot 2022-09-07 at 14 33 25" src="https://user-images.githubusercontent.com/79087014/188880594-e75ef65e-331f-4396-8297-c2f4bd76e8c7.png">

The cohort list has no pagination, 

<img width="473" alt="Screen Shot 2022-09-07 at 12 56 57" src="https://user-images.githubusercontent.com/79087014/188880849-92919ba6-2904-42c6-b3a9-47605ca2c38d.png">
The above is on the ratings, when logged in as coordinator

2022-09-07 14:32 UTC, Dev-nkundineza approved these changes
Good Work

2022-09-07 14:34 UTC, merged